// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/ip_transport.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IpAddrFamily: IP Address family
type IpAddrFamily int32

const (
	// undefined ip version
	IpAddrFamily_IPV_UNDEF IpAddrFamily = 0
	// IPv4
	IpAddrFamily_IPV4 IpAddrFamily = 1
	// IPv6
	IpAddrFamily_IPV6 IpAddrFamily = 2
)

// Enum value maps for IpAddrFamily.
var (
	IpAddrFamily_name = map[int32]string{
		0: "IPV_UNDEF",
		1: "IPV4",
		2: "IPV6",
	}
	IpAddrFamily_value = map[string]int32{
		"IPV_UNDEF": 0,
		"IPV4":      1,
		"IPV6":      2,
	}
)

func (x IpAddrFamily) Enum() *IpAddrFamily {
	p := new(IpAddrFamily)
	*p = x
	return p
}

func (x IpAddrFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpAddrFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[0].Descriptor()
}

func (IpAddrFamily) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[0]
}

func (x IpAddrFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpAddrFamily.Descriptor instead.
func (IpAddrFamily) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0}
}

// Protocol: represents supported network protocols
type Transport_Protocol int32

const (
	// PROTOCOL_UNDEF: not specified
	Transport_PROTOCOL_UNDEF Transport_Protocol = 0
	// TCP
	Transport_TCP Transport_Protocol = 1
	// UDP
	Transport_UDP Transport_Protocol = 2
	// ICMP
	Transport_ICMP Transport_Protocol = 3
)

// Enum value maps for Transport_Protocol.
var (
	Transport_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNDEF",
		1: "TCP",
		2: "UDP",
		3: "ICMP",
	}
	Transport_Protocol_value = map[string]int32{
		"PROTOCOL_UNDEF": 0,
		"TCP":            1,
		"UDP":            2,
		"ICMP":           3,
	}
)

func (x Transport_Protocol) Enum() *Transport_Protocol {
	p := new(Transport_Protocol)
	*p = x
	return p
}

func (x Transport_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[1].Descriptor()
}

func (Transport_Protocol) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[1]
}

func (x Transport_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport_Protocol.Descriptor instead.
func (Transport_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0}
}

// Ingress / Egress traffic dir
type Session_Traffic int32

const (
	// TRAFFIC_UNDEF not specified
	Session_TRAFFIC_UNDEF Session_Traffic = 0
	// Both ingress and egress
	Session_BOTH Session_Traffic = 1
	// Ingress
	Session_INGRESS Session_Traffic = 2
	// Egress
	Session_EGRESS Session_Traffic = 3
)

// Enum value maps for Session_Traffic.
var (
	Session_Traffic_name = map[int32]string{
		0: "TRAFFIC_UNDEF",
		1: "BOTH",
		2: "INGRESS",
		3: "EGRESS",
	}
	Session_Traffic_value = map[string]int32{
		"TRAFFIC_UNDEF": 0,
		"BOTH":          1,
		"INGRESS":       2,
		"EGRESS":        3,
	}
)

func (x Session_Traffic) Enum() *Session_Traffic {
	p := new(Session_Traffic)
	*p = x
	return p
}

func (x Session_Traffic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Session_Traffic) Descriptor() protoreflect.EnumDescriptor {
	return file_common_ip_transport_proto_enumTypes[2].Descriptor()
}

func (Session_Traffic) Type() protoreflect.EnumType {
	return &file_common_ip_transport_proto_enumTypes[2]
}

func (x Session_Traffic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Session_Traffic.Descriptor instead.
func (Session_Traffic) EnumDescriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{1, 0}
}

// Transport: represents supported network transports (L4)
type Transport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol: network protocol
	Protocol Transport_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=common.Transport_Protocol" json:"protocol,omitempty"`
	// IPv: IP address family
	Ipv IpAddrFamily `protobuf:"varint,2,opt,name=ipv,json=IPv,proto3,enum=common.IpAddrFamily" json:"ipv,omitempty"`
	// Entries: list of transport entries
	Entries       []*Transport_Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_common_ip_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Transport) GetProtocol() Transport_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Transport_PROTOCOL_UNDEF
}

func (x *Transport) GetIpv() IpAddrFamily {
	if x != nil {
		return x.Ipv
	}
	return IpAddrFamily_IPV_UNDEF
}

func (x *Transport) GetEntries() []*Transport_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Session: represents session parameters
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traffic: traffic direction
	Traffic       Session_Traffic `protobuf:"varint,1,opt,name=traffic,proto3,enum=common.Session_Traffic" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_common_ip_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetTraffic() Session_Traffic {
	if x != nil {
		return x.Traffic
	}
	return Session_TRAFFIC_UNDEF
}

// IPs: represents list of IP addresses
type IPs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ipv4: list of IPv4 addresses
	Ipv4 []string `protobuf:"bytes,1,rep,name=ipv4,json=IPv4,proto3" json:"ipv4,omitempty"`
	// Ipv6: list of IPv6 addresses
	Ipv6          []string `protobuf:"bytes,2,rep,name=ipv6,json=IPv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPs) Reset() {
	*x = IPs{}
	mi := &file_common_ip_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPs) ProtoMessage() {}

func (x *IPs) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPs.ProtoReflect.Descriptor instead.
func (*IPs) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{2}
}

func (x *IPs) GetIpv4() []string {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *IPs) GetIpv6() []string {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// Entry: represents transport entry
type Transport_Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description: description
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Comment: comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Ports: represents TCP/UDP port or port range
	Ports string `protobuf:"bytes,3,opt,name=ports,proto3" json:"ports,omitempty"`
	// Types: ICMP message types
	Types         []uint32 `protobuf:"varint,4,rep,packed,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_Entry) Reset() {
	*x = Transport_Entry{}
	mi := &file_common_ip_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_Entry) ProtoMessage() {}

func (x *Transport_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_common_ip_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_Entry.ProtoReflect.Descriptor instead.
func (*Transport_Entry) Descriptor() ([]byte, []int) {
	return file_common_ip_transport_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transport_Entry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transport_Entry) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Transport_Entry) GetPorts() string {
	if x != nil {
		return x.Ports
	}
	return ""
}

func (x *Transport_Entry) GetTypes() []uint32 {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_common_ip_transport_proto protoreflect.FileDescriptor

const file_common_ip_transport_proto_rawDesc = "" +
	"\n" +
	"\x19common/ip_transport.proto\x12\x06common\"\xcb\x02\n" +
	"\tTransport\x126\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1a.common.Transport.ProtocolR\bprotocol\x12&\n" +
	"\x03ipv\x18\x02 \x01(\x0e2\x14.common.IpAddrFamilyR\x03IPv\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.common.Transport.EntryR\aentries\x1ao\n" +
	"\x05Entry\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x14\n" +
	"\x05ports\x18\x03 \x01(\tR\x05ports\x12\x14\n" +
	"\x05types\x18\x04 \x03(\rR\x05types\":\n" +
	"\bProtocol\x12\x12\n" +
	"\x0ePROTOCOL_UNDEF\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02\x12\b\n" +
	"\x04ICMP\x10\x03\"}\n" +
	"\aSession\x121\n" +
	"\atraffic\x18\x01 \x01(\x0e2\x17.common.Session.TrafficR\atraffic\"?\n" +
	"\aTraffic\x12\x11\n" +
	"\rTRAFFIC_UNDEF\x10\x00\x12\b\n" +
	"\x04BOTH\x10\x01\x12\v\n" +
	"\aINGRESS\x10\x02\x12\n" +
	"\n" +
	"\x06EGRESS\x10\x03\"-\n" +
	"\x03IPs\x12\x12\n" +
	"\x04ipv4\x18\x01 \x03(\tR\x04IPv4\x12\x12\n" +
	"\x04ipv6\x18\x02 \x03(\tR\x04IPv6*1\n" +
	"\fIpAddrFamily\x12\r\n" +
	"\tIPV_UNDEF\x10\x00\x12\b\n" +
	"\x04IPV4\x10\x01\x12\b\n" +
	"\x04IPV6\x10\x02B=Z;github.com/PRO-Robotech/sgroups-proto/pkg/api/common;commonb\x06proto3"

var (
	file_common_ip_transport_proto_rawDescOnce sync.Once
	file_common_ip_transport_proto_rawDescData []byte
)

func file_common_ip_transport_proto_rawDescGZIP() []byte {
	file_common_ip_transport_proto_rawDescOnce.Do(func() {
		file_common_ip_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_ip_transport_proto_rawDesc), len(file_common_ip_transport_proto_rawDesc)))
	})
	return file_common_ip_transport_proto_rawDescData
}

var file_common_ip_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_ip_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_ip_transport_proto_goTypes = []any{
	(IpAddrFamily)(0),       // 0: common.IpAddrFamily
	(Transport_Protocol)(0), // 1: common.Transport.Protocol
	(Session_Traffic)(0),    // 2: common.Session.Traffic
	(*Transport)(nil),       // 3: common.Transport
	(*Session)(nil),         // 4: common.Session
	(*IPs)(nil),             // 5: common.IPs
	(*Transport_Entry)(nil), // 6: common.Transport.Entry
}
var file_common_ip_transport_proto_depIdxs = []int32{
	1, // 0: common.Transport.protocol:type_name -> common.Transport.Protocol
	0, // 1: common.Transport.ipv:type_name -> common.IpAddrFamily
	6, // 2: common.Transport.entries:type_name -> common.Transport.Entry
	2, // 3: common.Session.traffic:type_name -> common.Session.Traffic
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_ip_transport_proto_init() }
func file_common_ip_transport_proto_init() {
	if File_common_ip_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_ip_transport_proto_rawDesc), len(file_common_ip_transport_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_ip_transport_proto_goTypes,
		DependencyIndexes: file_common_ip_transport_proto_depIdxs,
		EnumInfos:         file_common_ip_transport_proto_enumTypes,
		MessageInfos:      file_common_ip_transport_proto_msgTypes,
	}.Build()
	File_common_ip_transport_proto = out.File
	file_common_ip_transport_proto_goTypes = nil
	file_common_ip_transport_proto_depIdxs = nil
}
