// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/resource.proto

package common

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action: enumeration of possible actions
type Action int32

const (
	// UNKNOWN: unknown action
	Action_UNKNOWN Action = 0
	// ALLOW: allow action
	Action_ALLOW Action = 1
	// DENY: deny action
	Action_DENY Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "UNKNOWN",
		1: "ALLOW",
		2: "DENY",
	}
	Action_value = map[string]int32{
		"UNKNOWN": 0,
		"ALLOW":   1,
		"DENY":    2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_common_resource_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_common_resource_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{0}
}

// WatchEventType: type of watch event
type WatchEventType int32

const (
	// EVENT_UNKNOWN: unknown event type
	WatchEventType_EVENT_UNKNOWN WatchEventType = 0
	// ADDED: object was created
	WatchEventType_ADDED WatchEventType = 1
	// MODIFIED: object was updated
	WatchEventType_MODIFIED WatchEventType = 2
	// DELETED: object was deleted
	WatchEventType_DELETED WatchEventType = 3
)

// Enum value maps for WatchEventType.
var (
	WatchEventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
	}
	WatchEventType_value = map[string]int32{
		"EVENT_UNKNOWN": 0,
		"ADDED":         1,
		"MODIFIED":      2,
		"DELETED":       3,
	}
)

func (x WatchEventType) Enum() *WatchEventType {
	p := new(WatchEventType)
	*p = x
	return p
}

func (x WatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_resource_proto_enumTypes[1].Descriptor()
}

func (WatchEventType) Type() protoreflect.EnumType {
	return &file_common_resource_proto_enumTypes[1]
}

func (x WatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEventType.Descriptor instead.
func (WatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{1}
}

// Type: endpoint type
type Endpoints_Type int32

const (
	// UNKNOWN: unknown type
	Endpoints_UNKNOWN Endpoints_Type = 0
	// ADDRESS_GROUP: address group type
	Endpoints_ADDRESS_GROUP Endpoints_Type = 1
	// SERVICE: service type
	Endpoints_SERVICE Endpoints_Type = 2
	// FQDN: FQDN type
	Endpoints_FQDN Endpoints_Type = 3
	// CIDR: CIDR type
	Endpoints_CIDR Endpoints_Type = 4
)

// Enum value maps for Endpoints_Type.
var (
	Endpoints_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADDRESS_GROUP",
		2: "SERVICE",
		3: "FQDN",
		4: "CIDR",
	}
	Endpoints_Type_value = map[string]int32{
		"UNKNOWN":       0,
		"ADDRESS_GROUP": 1,
		"SERVICE":       2,
		"FQDN":          3,
		"CIDR":          4,
	}
)

func (x Endpoints_Type) Enum() *Endpoints_Type {
	p := new(Endpoints_Type)
	*p = x
	return p
}

func (x Endpoints_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Endpoints_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_common_resource_proto_enumTypes[2].Descriptor()
}

func (Endpoints_Type) Type() protoreflect.EnumType {
	return &file_common_resource_proto_enumTypes[2]
}

func (x Endpoints_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Endpoints_Type.Descriptor instead.
func (Endpoints_Type) EnumDescriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{6, 0}
}

// Metadata: common resource metadata
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID: unique identifier. Use this for update requests; for create requests, leave it empty
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Name: resource name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Labels: resource labels
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations: resource annotations
	Annotations map[string]string `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// CreationTimestamp: resource creation timestamp
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	// ResourceVersion: resource revision version
	ResourceVersion string `protobuf:"bytes,7,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_common_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Metadata) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *Metadata) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

// MetadataScope: common resource metadata for scoping
type MetadataScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID: unique identifier. Use this for update requests; for create requests, leave it empty
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Name: resource name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataScope) Reset() {
	*x = MetadataScope{}
	mi := &file_common_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataScope) ProtoMessage() {}

func (x *MetadataScope) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataScope.ProtoReflect.Descriptor instead.
func (*MetadataScope) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataScope) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MetadataScope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataScope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ResourceRef: reference to a resource
type ResourceRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: reference resource name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: reference resource namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// ResType: reference resource type
	ResType       string `protobuf:"bytes,3,opt,name=res_type,json=resType,proto3" json:"res_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_common_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRef) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

// FieldSelector: resource field selector
type FieldSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: resource name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Refs: resource references
	Refs          []*ResourceRef `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSelector) Reset() {
	*x = FieldSelector{}
	mi := &file_common_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSelector) ProtoMessage() {}

func (x *FieldSelector) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSelector.ProtoReflect.Descriptor instead.
func (*FieldSelector) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{3}
}

func (x *FieldSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldSelector) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FieldSelector) GetRefs() []*ResourceRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

// ResSelector: resource selector for list requests
type ResSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FieldSelector: field selector
	FieldSelector *FieldSelector `protobuf:"bytes,1,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	// LabelSelector: label selector
	LabelSelector map[string]string `protobuf:"bytes,2,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResSelector) Reset() {
	*x = ResSelector{}
	mi := &file_common_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSelector) ProtoMessage() {}

func (x *ResSelector) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSelector.ProtoReflect.Descriptor instead.
func (*ResSelector) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ResSelector) GetFieldSelector() *FieldSelector {
	if x != nil {
		return x.FieldSelector
	}
	return nil
}

func (x *ResSelector) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

// ResourceIdentifier: resource identifier
type ResourceIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: resource name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: resource namespace
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceIdentifier) Reset() {
	*x = ResourceIdentifier{}
	mi := &file_common_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIdentifier) ProtoMessage() {}

func (x *ResourceIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIdentifier.ProtoReflect.Descriptor instead.
func (*ResourceIdentifier) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceIdentifier) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Endpoints: represents endpoints
type Endpoints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local: local endpoint
	Local *Endpoints_Local `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	// Remote: remote endpoint
	Remote        *Endpoints_Remote `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoints) Reset() {
	*x = Endpoints{}
	mi := &file_common_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoints) ProtoMessage() {}

func (x *Endpoints) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoints.ProtoReflect.Descriptor instead.
func (*Endpoints) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{6}
}

func (x *Endpoints) GetLocal() *Endpoints_Local {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *Endpoints) GetRemote() *Endpoints_Remote {
	if x != nil {
		return x.Remote
	}
	return nil
}

// Local: local endpoint
type Endpoints_Local struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: endpoint name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: endpoint namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Type: endpoint type
	Type Endpoints_Type `protobuf:"varint,3,opt,name=type,proto3,enum=common.Endpoints_Type" json:"type,omitempty"`
	// Labels: resource labels
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoints_Local) Reset() {
	*x = Endpoints_Local{}
	mi := &file_common_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoints_Local) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoints_Local) ProtoMessage() {}

func (x *Endpoints_Local) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoints_Local.ProtoReflect.Descriptor instead.
func (*Endpoints_Local) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Endpoints_Local) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoints_Local) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Endpoints_Local) GetType() Endpoints_Type {
	if x != nil {
		return x.Type
	}
	return Endpoints_UNKNOWN
}

func (x *Endpoints_Local) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Remote: remote endpoint
type Endpoints_Remote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: endpoint name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace: endpoint namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Type: endpoint type
	Type Endpoints_Type `protobuf:"varint,3,opt,name=type,proto3,enum=common.Endpoints_Type" json:"type,omitempty"`
	// Value: endpoint value
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Labels: resource labels
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoints_Remote) Reset() {
	*x = Endpoints_Remote{}
	mi := &file_common_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoints_Remote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoints_Remote) ProtoMessage() {}

func (x *Endpoints_Remote) ProtoReflect() protoreflect.Message {
	mi := &file_common_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoints_Remote.ProtoReflect.Descriptor instead.
func (*Endpoints_Remote) Descriptor() ([]byte, []int) {
	return file_common_resource_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Endpoints_Remote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoints_Remote) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Endpoints_Remote) GetType() Endpoints_Type {
	if x != nil {
		return x.Type
	}
	return Endpoints_UNKNOWN
}

func (x *Endpoints_Remote) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Endpoints_Remote) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_common_resource_proto protoreflect.FileDescriptor

const file_common_resource_proto_rawDesc = "" +
	"\n" +
	"\x15common/resource.proto\x12\x06common\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x98\x06\n" +
	"\bMetadata\x12\xea\x01\n" +
	"\x03uid\x18\x01 \x01(\tB\xd7\x01\x92A\xd3\x01*\x03uid2Uid of the resource. Use this for update requests; for create requests, leave it emptyJ&\"2438ac3c-37eb-4902-adef-ed16b4431030\"\x8a\x01E^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$\xa2\x02\x04uuidR\x03uid\x12H\n" +
	"\x04name\x18\x02 \x01(\tB4\xbaH1\xd8\x01\x01r,\x10\x01\x18?2&^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$R\x04name\x12U\n" +
	"\tnamespace\x18\x03 \x01(\tB7\xe0A\x01\xbaH1\xd8\x01\x01r,\x10\x01\x18?2&^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$R\tnamespace\x124\n" +
	"\x06labels\x18\x04 \x03(\v2\x1c.common.Metadata.LabelsEntryR\x06labels\x12C\n" +
	"\vannotations\x18\x05 \x03(\v2!.common.Metadata.AnnotationsEntryR\vannotations\x12S\n" +
	"\x12creation_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\x92A\x02@\x01\xe0A\x03R\x11creationTimestamp\x123\n" +
	"\x10resource_version\x18\a \x01(\tB\b\x92A\x02@\x01\xe0A\x03R\x0fresourceVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\rMetadataScope\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"Z\n" +
	"\vResourceRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bres_type\x18\x03 \x01(\tR\aresType\"j\n" +
	"\rFieldSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12'\n" +
	"\x04refs\x18\x03 \x03(\v2\x13.common.ResourceRefR\x04refs\"\xdc\x01\n" +
	"\vResSelector\x12<\n" +
	"\x0efield_selector\x18\x01 \x01(\v2\x15.common.FieldSelectorR\rfieldSelector\x12M\n" +
	"\x0elabel_selector\x18\x02 \x03(\v2&.common.ResSelector.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x12ResourceIdentifier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x8d\x05\n" +
	"\tEndpoints\x12-\n" +
	"\x05local\x18\x01 \x01(\v2\x17.common.Endpoints.LocalR\x05local\x120\n" +
	"\x06remote\x18\x02 \x01(\v2\x18.common.Endpoints.RemoteR\x06remote\x1a\xdd\x01\n" +
	"\x05Local\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.common.Endpoints.TypeR\x04type\x12;\n" +
	"\x06labels\x18\x04 \x03(\v2#.common.Endpoints.Local.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xf5\x01\n" +
	"\x06Remote\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.common.Endpoints.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12<\n" +
	"\x06labels\x18\x05 \x03(\v2$.common.Endpoints.Remote.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rADDRESS_GROUP\x10\x01\x12\v\n" +
	"\aSERVICE\x10\x02\x12\b\n" +
	"\x04FQDN\x10\x03\x12\b\n" +
	"\x04CIDR\x10\x04**\n" +
	"\x06Action\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02*I\n" +
	"\x0eWatchEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\t\n" +
	"\x05ADDED\x10\x01\x12\f\n" +
	"\bMODIFIED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03B=Z;github.com/PRO-Robotech/sgroups-proto/pkg/api/common;commonb\x06proto3"

var (
	file_common_resource_proto_rawDescOnce sync.Once
	file_common_resource_proto_rawDescData []byte
)

func file_common_resource_proto_rawDescGZIP() []byte {
	file_common_resource_proto_rawDescOnce.Do(func() {
		file_common_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_resource_proto_rawDesc), len(file_common_resource_proto_rawDesc)))
	})
	return file_common_resource_proto_rawDescData
}

var file_common_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_common_resource_proto_goTypes = []any{
	(Action)(0),                   // 0: common.Action
	(WatchEventType)(0),           // 1: common.WatchEventType
	(Endpoints_Type)(0),           // 2: common.Endpoints.Type
	(*Metadata)(nil),              // 3: common.Metadata
	(*MetadataScope)(nil),         // 4: common.MetadataScope
	(*ResourceRef)(nil),           // 5: common.ResourceRef
	(*FieldSelector)(nil),         // 6: common.FieldSelector
	(*ResSelector)(nil),           // 7: common.ResSelector
	(*ResourceIdentifier)(nil),    // 8: common.ResourceIdentifier
	(*Endpoints)(nil),             // 9: common.Endpoints
	nil,                           // 10: common.Metadata.LabelsEntry
	nil,                           // 11: common.Metadata.AnnotationsEntry
	nil,                           // 12: common.ResSelector.LabelSelectorEntry
	(*Endpoints_Local)(nil),       // 13: common.Endpoints.Local
	(*Endpoints_Remote)(nil),      // 14: common.Endpoints.Remote
	nil,                           // 15: common.Endpoints.Local.LabelsEntry
	nil,                           // 16: common.Endpoints.Remote.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_common_resource_proto_depIdxs = []int32{
	10, // 0: common.Metadata.labels:type_name -> common.Metadata.LabelsEntry
	11, // 1: common.Metadata.annotations:type_name -> common.Metadata.AnnotationsEntry
	17, // 2: common.Metadata.creation_timestamp:type_name -> google.protobuf.Timestamp
	5,  // 3: common.FieldSelector.refs:type_name -> common.ResourceRef
	6,  // 4: common.ResSelector.field_selector:type_name -> common.FieldSelector
	12, // 5: common.ResSelector.label_selector:type_name -> common.ResSelector.LabelSelectorEntry
	13, // 6: common.Endpoints.local:type_name -> common.Endpoints.Local
	14, // 7: common.Endpoints.remote:type_name -> common.Endpoints.Remote
	2,  // 8: common.Endpoints.Local.type:type_name -> common.Endpoints.Type
	15, // 9: common.Endpoints.Local.labels:type_name -> common.Endpoints.Local.LabelsEntry
	2,  // 10: common.Endpoints.Remote.type:type_name -> common.Endpoints.Type
	16, // 11: common.Endpoints.Remote.labels:type_name -> common.Endpoints.Remote.LabelsEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_common_resource_proto_init() }
func file_common_resource_proto_init() {
	if File_common_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_resource_proto_rawDesc), len(file_common_resource_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_resource_proto_goTypes,
		DependencyIndexes: file_common_resource_proto_depIdxs,
		EnumInfos:         file_common_resource_proto_enumTypes,
		MessageInfos:      file_common_resource_proto_msgTypes,
	}.Build()
	File_common_resource_proto = out.File
	file_common_resource_proto_goTypes = nil
	file_common_resource_proto_depIdxs = nil
}
