// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sgroups/v1/domains.proto

package sgroupsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/PRO-Robotech/sgroups-proto/pkg/api/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Namespace: represents namespace resource
type Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: namespace metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: namespace specification
	Spec          *Namespace_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Namespace) GetSpec() *Namespace_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// AddressGroup: represents address group resource
type AddressGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: address group metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: address group specification
	Spec          *AddressGroup_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressGroup) Reset() {
	*x = AddressGroup{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressGroup) ProtoMessage() {}

func (x *AddressGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressGroup.ProtoReflect.Descriptor instead.
func (*AddressGroup) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{1}
}

func (x *AddressGroup) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AddressGroup) GetSpec() *AddressGroup_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Network: represents network resource
type Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: network metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: network specification
	Spec          *Network_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{2}
}

func (x *Network) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Network) GetSpec() *Network_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Host: represents host resource
type Host struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: host metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: host specification
	Spec          *Host_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{3}
}

func (x *Host) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Host) GetSpec() *Host_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// HostBinding: represents host binding resource
type HostBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: host binding metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: host binding specification
	Spec          *HostBinding_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostBinding) Reset() {
	*x = HostBinding{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBinding) ProtoMessage() {}

func (x *HostBinding) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBinding.ProtoReflect.Descriptor instead.
func (*HostBinding) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{4}
}

func (x *HostBinding) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HostBinding) GetSpec() *HostBinding_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// NetworkBinding: represents network binding resource
type NetworkBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: network binding metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: network binding specification
	Spec          *NetworkBinding_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinding) Reset() {
	*x = NetworkBinding{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinding) ProtoMessage() {}

func (x *NetworkBinding) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinding.ProtoReflect.Descriptor instead.
func (*NetworkBinding) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkBinding) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NetworkBinding) GetSpec() *NetworkBinding_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Service: represents service resource with transport specifications
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: service metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: service specification
	Spec          *Service_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{6}
}

func (x *Service) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Service) GetSpec() *Service_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// ServiceBinding: represents service binding resource
type ServiceBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: service binding metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: service binding specification
	Spec          *ServiceBinding_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceBinding) Reset() {
	*x = ServiceBinding{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBinding) ProtoMessage() {}

func (x *ServiceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBinding.ProtoReflect.Descriptor instead.
func (*ServiceBinding) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceBinding) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceBinding) GetSpec() *ServiceBinding_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Rule: represents rule resource
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata: rule metadata
	Metadata *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec: rule specification
	Spec          *Rule_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{8}
}

func (x *Rule) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Rule) GetSpec() *Rule_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Spec: resource specification
type Namespace_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace_Spec) Reset() {
	*x = Namespace_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace_Spec) ProtoMessage() {}

func (x *Namespace_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace_Spec.ProtoReflect.Descriptor instead.
func (*Namespace_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Namespace_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Namespace_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Namespace_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Spec: resource specification
type AddressGroup_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// DefaultAction: default action for the address group
	DefaultAction common.Action `protobuf:"varint,4,opt,name=default_action,json=defaultAction,proto3,enum=common.Action" json:"default_action,omitempty"`
	// Logs: enable logging
	Logs bool `protobuf:"varint,5,opt,name=logs,proto3" json:"logs,omitempty"`
	// Trace: enable flow logging
	Trace         bool `protobuf:"varint,6,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressGroup_Spec) Reset() {
	*x = AddressGroup_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressGroup_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressGroup_Spec) ProtoMessage() {}

func (x *AddressGroup_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressGroup_Spec.ProtoReflect.Descriptor instead.
func (*AddressGroup_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AddressGroup_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AddressGroup_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AddressGroup_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddressGroup_Spec) GetDefaultAction() common.Action {
	if x != nil {
		return x.DefaultAction
	}
	return common.Action(0)
}

func (x *AddressGroup_Spec) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *AddressGroup_Spec) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

// Spec: resource specification
type Network_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// CIDR: network CIDR
	Cidr          string `protobuf:"bytes,4,opt,name=cidr,json=CIDR,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network_Spec) Reset() {
	*x = Network_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network_Spec) ProtoMessage() {}

func (x *Network_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network_Spec.ProtoReflect.Descriptor instead.
func (*Network_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Network_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Network_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Network_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Network_Spec) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

// Spec: resource specification
type Host_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// IPs: list of IP addresses associated with the host
	Ips *common.IPs `protobuf:"bytes,4,opt,name=ips,json=IPs,proto3" json:"ips,omitempty"`
	// MetaInfo: host meta information
	MetaInfo *Host_Spec_MetaInfo `protobuf:"bytes,5,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	// Endpoints: endpoints published by the host
	Endpoints     *Host_Spec_Endpoints `protobuf:"bytes,6,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host_Spec) Reset() {
	*x = Host_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host_Spec) ProtoMessage() {}

func (x *Host_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host_Spec.ProtoReflect.Descriptor instead.
func (*Host_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Host_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Host_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Host_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Host_Spec) GetIps() *common.IPs {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *Host_Spec) GetMetaInfo() *Host_Spec_MetaInfo {
	if x != nil {
		return x.MetaInfo
	}
	return nil
}

func (x *Host_Spec) GetEndpoints() *Host_Spec_Endpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// MetaInfo: represents host meta information
type Host_Spec_MetaInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HostName: host name
	HostName string `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	// Os: host operating system
	Os string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	// Platform: host platform
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// PlatformFamily: host platform family
	PlatformFamily string `protobuf:"bytes,4,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`
	// PlatformVersion: host platform version
	PlatformVersion string `protobuf:"bytes,5,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	// KernelVersion: host kernel version
	KernelVersion string `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host_Spec_MetaInfo) Reset() {
	*x = Host_Spec_MetaInfo{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host_Spec_MetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host_Spec_MetaInfo) ProtoMessage() {}

func (x *Host_Spec_MetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host_Spec_MetaInfo.ProtoReflect.Descriptor instead.
func (*Host_Spec_MetaInfo) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *Host_Spec_MetaInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Host_Spec_MetaInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Host_Spec_MetaInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Host_Spec_MetaInfo) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *Host_Spec_MetaInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *Host_Spec_MetaInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

// Endpoints: represents host endpoints
type Host_Spec_Endpoints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address: endpoint address is reachable at. If empty, the server
	// falls back to the peer address observed on the gRPC connection.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Ports: list of ports.
	Ports         []*Host_Spec_Endpoints_Port `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host_Spec_Endpoints) Reset() {
	*x = Host_Spec_Endpoints{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host_Spec_Endpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host_Spec_Endpoints) ProtoMessage() {}

func (x *Host_Spec_Endpoints) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host_Spec_Endpoints.ProtoReflect.Descriptor instead.
func (*Host_Spec_Endpoints) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *Host_Spec_Endpoints) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Host_Spec_Endpoints) GetPorts() []*Host_Spec_Endpoints_Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

// Port: port with a logical name to identify what it serves.
type Host_Spec_Endpoints_Port struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name: logical port name (e.g. "api", "metrics", "health").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Port: TCP/UDP port number.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host_Spec_Endpoints_Port) Reset() {
	*x = Host_Spec_Endpoints_Port{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host_Spec_Endpoints_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host_Spec_Endpoints_Port) ProtoMessage() {}

func (x *Host_Spec_Endpoints_Port) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host_Spec_Endpoints_Port.ProtoReflect.Descriptor instead.
func (*Host_Spec_Endpoints_Port) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{3, 0, 1, 0}
}

func (x *Host_Spec_Endpoints_Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Host_Spec_Endpoints_Port) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Spec: resource specification
type HostBinding_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// AddressGroup: reference to the address group
	AddressGroup *common.ResourceIdentifier `protobuf:"bytes,4,opt,name=address_group,json=addressGroup,proto3" json:"address_group,omitempty"`
	// Host: reference to the host
	Host          *common.ResourceIdentifier `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostBinding_Spec) Reset() {
	*x = HostBinding_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostBinding_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBinding_Spec) ProtoMessage() {}

func (x *HostBinding_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBinding_Spec.ProtoReflect.Descriptor instead.
func (*HostBinding_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{4, 0}
}

func (x *HostBinding_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *HostBinding_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *HostBinding_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HostBinding_Spec) GetAddressGroup() *common.ResourceIdentifier {
	if x != nil {
		return x.AddressGroup
	}
	return nil
}

func (x *HostBinding_Spec) GetHost() *common.ResourceIdentifier {
	if x != nil {
		return x.Host
	}
	return nil
}

// Spec: resource specification
type NetworkBinding_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// AddressGroup: reference to the address group
	AddressGroup *common.ResourceIdentifier `protobuf:"bytes,4,opt,name=address_group,json=addressGroup,proto3" json:"address_group,omitempty"`
	// Network: reference to the network
	Network       *common.ResourceIdentifier `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinding_Spec) Reset() {
	*x = NetworkBinding_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinding_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinding_Spec) ProtoMessage() {}

func (x *NetworkBinding_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinding_Spec.ProtoReflect.Descriptor instead.
func (*NetworkBinding_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{5, 0}
}

func (x *NetworkBinding_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NetworkBinding_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *NetworkBinding_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NetworkBinding_Spec) GetAddressGroup() *common.ResourceIdentifier {
	if x != nil {
		return x.AddressGroup
	}
	return nil
}

func (x *NetworkBinding_Spec) GetNetwork() *common.ResourceIdentifier {
	if x != nil {
		return x.Network
	}
	return nil
}

// Spec: resource specification
type Service_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Transports: transport protocol specifications
	Transports    []*common.Transport `protobuf:"bytes,4,rep,name=transports,proto3" json:"transports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service_Spec) Reset() {
	*x = Service_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Spec) ProtoMessage() {}

func (x *Service_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Spec.ProtoReflect.Descriptor instead.
func (*Service_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Service_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Service_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Service_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service_Spec) GetTransports() []*common.Transport {
	if x != nil {
		return x.Transports
	}
	return nil
}

// Spec: resource specification
type ServiceBinding_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// AddressGroup: reference to the address group
	AddressGroup *common.ResourceIdentifier `protobuf:"bytes,4,opt,name=address_group,json=addressGroup,proto3" json:"address_group,omitempty"`
	// Service: reference to the service
	Service       *common.ResourceIdentifier `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceBinding_Spec) Reset() {
	*x = ServiceBinding_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBinding_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBinding_Spec) ProtoMessage() {}

func (x *ServiceBinding_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBinding_Spec.ProtoReflect.Descriptor instead.
func (*ServiceBinding_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ServiceBinding_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceBinding_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ServiceBinding_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceBinding_Spec) GetAddressGroup() *common.ResourceIdentifier {
	if x != nil {
		return x.AddressGroup
	}
	return nil
}

func (x *ServiceBinding_Spec) GetService() *common.ResourceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

// Spec: resource specification
type Rule_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DisplayName: resource display name
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Comment: resource comment
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// Description: resource description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Action: rule action
	Action common.Action `protobuf:"varint,4,opt,name=action,proto3,enum=common.Action" json:"action,omitempty"`
	// Session: session parameters
	Session *common.Session `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	// Endpoints: local and remote endpoints
	Endpoints *common.Endpoints `protobuf:"bytes,6,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Transport: network transport
	Transport     *common.Transport `protobuf:"bytes,7,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule_Spec) Reset() {
	*x = Rule_Spec{}
	mi := &file_sgroups_v1_domains_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_Spec) ProtoMessage() {}

func (x *Rule_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sgroups_v1_domains_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_Spec.ProtoReflect.Descriptor instead.
func (*Rule_Spec) Descriptor() ([]byte, []int) {
	return file_sgroups_v1_domains_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Rule_Spec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Rule_Spec) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Rule_Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule_Spec) GetAction() common.Action {
	if x != nil {
		return x.Action
	}
	return common.Action(0)
}

func (x *Rule_Spec) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Rule_Spec) GetEndpoints() *common.Endpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Rule_Spec) GetTransport() *common.Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

var File_sgroups_v1_domains_proto protoreflect.FileDescriptor

const file_sgroups_v1_domains_proto_rawDesc = "" +
	"\n" +
	"\x18sgroups/v1/domains.proto\x12\n" +
	"sgroups.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19common/ip_transport.proto\x1a\x15common/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe9\x01\n" +
	"\tNamespace\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x126\n" +
	"\x04spec\x18\x02 \x01(\v2\x1a.sgroups.v1.Namespace.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1an\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xdb\x02\n" +
	"\fAddressGroup\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x129\n" +
	"\x04spec\x18\x02 \x01(\v2\x1d.sgroups.v1.AddressGroup.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xd9\x01\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\x0edefault_action\x18\x04 \x01(\x0e2\x0e.common.ActionB\b\xbaH\x05\x82\x01\x02 \x00R\rdefaultAction\x12\x12\n" +
	"\x04logs\x18\x05 \x01(\bR\x04logs\x12\x14\n" +
	"\x05trace\x18\x06 \x01(\bR\x05trace\"\xf6\x02\n" +
	"\aNetwork\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x124\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.sgroups.v1.Network.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xfe\x01\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x8d\x01\n" +
	"\x04cidr\x18\x04 \x01(\tBy\xbaHv\xba\x01F\x12/must not contain leading or trailing whitespace\x1a\x13this == this.trim()\xba\x01&\x12\x10must contain '/'\x1a\x12this.contains('/')r\x02\x10\x01R\x04CIDR\"\x94\x06\n" +
	"\x04Host\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x121\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.sgroups.v1.Host.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xa2\x05\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x03ips\x18\x04 \x01(\v2\v.common.IPsB\b\x92A\x02@\x01\xe0A\x03R\x03IPs\x12E\n" +
	"\tmeta_info\x18\x05 \x01(\v2\x1e.sgroups.v1.Host.Spec.MetaInfoB\b\x92A\x02@\x01\xe0A\x03R\bmetaInfo\x12G\n" +
	"\tendpoints\x18\x06 \x01(\v2\x1f.sgroups.v1.Host.Spec.EndpointsB\b\x92A\x02@\x01\xe0A\x03R\tendpoints\x1a\xce\x01\n" +
	"\bMetaInfo\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\x04 \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\x05 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x1a\xa7\x01\n" +
	"\tEndpoints\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12:\n" +
	"\x05ports\x18\x02 \x03(\v2$.sgroups.v1.Host.Spec.Endpoints.PortR\x05ports\x1aD\n" +
	"\x04Port\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\x04name\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\"\xef\x02\n" +
	"\vHostBinding\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x128\n" +
	"\x04spec\x18\x02 \x01(\v2\x1c.sgroups.v1.HostBinding.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xef\x01\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12G\n" +
	"\raddress_group\x18\x04 \x01(\v2\x1a.common.ResourceIdentifierB\x06\xbaH\x03\xc8\x01\x01R\faddressGroup\x126\n" +
	"\x04host\x18\x05 \x01(\v2\x1a.common.ResourceIdentifierB\x06\xbaH\x03\xc8\x01\x01R\x04host\"\xfb\x02\n" +
	"\x0eNetworkBinding\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.sgroups.v1.NetworkBinding.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xf5\x01\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12G\n" +
	"\raddress_group\x18\x04 \x01(\v2\x1a.common.ResourceIdentifierB\x06\xbaH\x03\xc8\x01\x01R\faddressGroup\x12<\n" +
	"\anetwork\x18\x05 \x01(\v2\x1a.common.ResourceIdentifierB\x06\xbaH\x03\xc8\x01\x01R\anetwork\"\x99\x02\n" +
	"\aService\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x124\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.sgroups.v1.Service.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xa1\x01\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\n" +
	"transports\x18\x04 \x03(\v2\x11.common.TransportR\n" +
	"transports\"\xfb\x02\n" +
	"\x0eServiceBinding\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.sgroups.v1.ServiceBinding.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xf5\x01\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12G\n" +
	"\raddress_group\x18\x04 \x01(\v2\x1a.common.ResourceIdentifierB\x06\xbaH\x03\xc8\x01\x01R\faddressGroup\x12<\n" +
	"\aservice\x18\x05 \x01(\v2\x1a.common.ResourceIdentifierB\x06\xbaH\x03\xc8\x01\x01R\aservice\"\x9f\x03\n" +
	"\x04Rule\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x121\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.sgroups.v1.Rule.SpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x1a\xad\x02\n" +
	"\x04Spec\x12*\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18?R\vdisplayName\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x06action\x18\x04 \x01(\x0e2\x0e.common.ActionB\b\xbaH\x05\x82\x01\x02 \x00R\x06action\x12)\n" +
	"\asession\x18\x05 \x01(\v2\x0f.common.SessionR\asession\x12/\n" +
	"\tendpoints\x18\x06 \x01(\v2\x11.common.EndpointsR\tendpoints\x12/\n" +
	"\ttransport\x18\a \x01(\v2\x11.common.TransportR\ttransportBDZBgithub.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1;sgroupsv1b\x06proto3"

var (
	file_sgroups_v1_domains_proto_rawDescOnce sync.Once
	file_sgroups_v1_domains_proto_rawDescData []byte
)

func file_sgroups_v1_domains_proto_rawDescGZIP() []byte {
	file_sgroups_v1_domains_proto_rawDescOnce.Do(func() {
		file_sgroups_v1_domains_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sgroups_v1_domains_proto_rawDesc), len(file_sgroups_v1_domains_proto_rawDesc)))
	})
	return file_sgroups_v1_domains_proto_rawDescData
}

var file_sgroups_v1_domains_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sgroups_v1_domains_proto_goTypes = []any{
	(*Namespace)(nil),                 // 0: sgroups.v1.Namespace
	(*AddressGroup)(nil),              // 1: sgroups.v1.AddressGroup
	(*Network)(nil),                   // 2: sgroups.v1.Network
	(*Host)(nil),                      // 3: sgroups.v1.Host
	(*HostBinding)(nil),               // 4: sgroups.v1.HostBinding
	(*NetworkBinding)(nil),            // 5: sgroups.v1.NetworkBinding
	(*Service)(nil),                   // 6: sgroups.v1.Service
	(*ServiceBinding)(nil),            // 7: sgroups.v1.ServiceBinding
	(*Rule)(nil),                      // 8: sgroups.v1.Rule
	(*Namespace_Spec)(nil),            // 9: sgroups.v1.Namespace.Spec
	(*AddressGroup_Spec)(nil),         // 10: sgroups.v1.AddressGroup.Spec
	(*Network_Spec)(nil),              // 11: sgroups.v1.Network.Spec
	(*Host_Spec)(nil),                 // 12: sgroups.v1.Host.Spec
	(*Host_Spec_MetaInfo)(nil),        // 13: sgroups.v1.Host.Spec.MetaInfo
	(*Host_Spec_Endpoints)(nil),       // 14: sgroups.v1.Host.Spec.Endpoints
	(*Host_Spec_Endpoints_Port)(nil),  // 15: sgroups.v1.Host.Spec.Endpoints.Port
	(*HostBinding_Spec)(nil),          // 16: sgroups.v1.HostBinding.Spec
	(*NetworkBinding_Spec)(nil),       // 17: sgroups.v1.NetworkBinding.Spec
	(*Service_Spec)(nil),              // 18: sgroups.v1.Service.Spec
	(*ServiceBinding_Spec)(nil),       // 19: sgroups.v1.ServiceBinding.Spec
	(*Rule_Spec)(nil),                 // 20: sgroups.v1.Rule.Spec
	(*common.Metadata)(nil),           // 21: common.Metadata
	(common.Action)(0),                // 22: common.Action
	(*common.IPs)(nil),                // 23: common.IPs
	(*common.ResourceIdentifier)(nil), // 24: common.ResourceIdentifier
	(*common.Transport)(nil),          // 25: common.Transport
	(*common.Session)(nil),            // 26: common.Session
	(*common.Endpoints)(nil),          // 27: common.Endpoints
}
var file_sgroups_v1_domains_proto_depIdxs = []int32{
	21, // 0: sgroups.v1.Namespace.metadata:type_name -> common.Metadata
	9,  // 1: sgroups.v1.Namespace.spec:type_name -> sgroups.v1.Namespace.Spec
	21, // 2: sgroups.v1.AddressGroup.metadata:type_name -> common.Metadata
	10, // 3: sgroups.v1.AddressGroup.spec:type_name -> sgroups.v1.AddressGroup.Spec
	21, // 4: sgroups.v1.Network.metadata:type_name -> common.Metadata
	11, // 5: sgroups.v1.Network.spec:type_name -> sgroups.v1.Network.Spec
	21, // 6: sgroups.v1.Host.metadata:type_name -> common.Metadata
	12, // 7: sgroups.v1.Host.spec:type_name -> sgroups.v1.Host.Spec
	21, // 8: sgroups.v1.HostBinding.metadata:type_name -> common.Metadata
	16, // 9: sgroups.v1.HostBinding.spec:type_name -> sgroups.v1.HostBinding.Spec
	21, // 10: sgroups.v1.NetworkBinding.metadata:type_name -> common.Metadata
	17, // 11: sgroups.v1.NetworkBinding.spec:type_name -> sgroups.v1.NetworkBinding.Spec
	21, // 12: sgroups.v1.Service.metadata:type_name -> common.Metadata
	18, // 13: sgroups.v1.Service.spec:type_name -> sgroups.v1.Service.Spec
	21, // 14: sgroups.v1.ServiceBinding.metadata:type_name -> common.Metadata
	19, // 15: sgroups.v1.ServiceBinding.spec:type_name -> sgroups.v1.ServiceBinding.Spec
	21, // 16: sgroups.v1.Rule.metadata:type_name -> common.Metadata
	20, // 17: sgroups.v1.Rule.spec:type_name -> sgroups.v1.Rule.Spec
	22, // 18: sgroups.v1.AddressGroup.Spec.default_action:type_name -> common.Action
	23, // 19: sgroups.v1.Host.Spec.ips:type_name -> common.IPs
	13, // 20: sgroups.v1.Host.Spec.meta_info:type_name -> sgroups.v1.Host.Spec.MetaInfo
	14, // 21: sgroups.v1.Host.Spec.endpoints:type_name -> sgroups.v1.Host.Spec.Endpoints
	15, // 22: sgroups.v1.Host.Spec.Endpoints.ports:type_name -> sgroups.v1.Host.Spec.Endpoints.Port
	24, // 23: sgroups.v1.HostBinding.Spec.address_group:type_name -> common.ResourceIdentifier
	24, // 24: sgroups.v1.HostBinding.Spec.host:type_name -> common.ResourceIdentifier
	24, // 25: sgroups.v1.NetworkBinding.Spec.address_group:type_name -> common.ResourceIdentifier
	24, // 26: sgroups.v1.NetworkBinding.Spec.network:type_name -> common.ResourceIdentifier
	25, // 27: sgroups.v1.Service.Spec.transports:type_name -> common.Transport
	24, // 28: sgroups.v1.ServiceBinding.Spec.address_group:type_name -> common.ResourceIdentifier
	24, // 29: sgroups.v1.ServiceBinding.Spec.service:type_name -> common.ResourceIdentifier
	22, // 30: sgroups.v1.Rule.Spec.action:type_name -> common.Action
	26, // 31: sgroups.v1.Rule.Spec.session:type_name -> common.Session
	27, // 32: sgroups.v1.Rule.Spec.endpoints:type_name -> common.Endpoints
	25, // 33: sgroups.v1.Rule.Spec.transport:type_name -> common.Transport
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_sgroups_v1_domains_proto_init() }
func file_sgroups_v1_domains_proto_init() {
	if File_sgroups_v1_domains_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgroups_v1_domains_proto_rawDesc), len(file_sgroups_v1_domains_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgroups_v1_domains_proto_goTypes,
		DependencyIndexes: file_sgroups_v1_domains_proto_depIdxs,
		MessageInfos:      file_sgroups_v1_domains_proto_msgTypes,
	}.Build()
	File_sgroups_v1_domains_proto = out.File
	file_sgroups_v1_domains_proto_goTypes = nil
	file_sgroups_v1_domains_proto_depIdxs = nil
}
