// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sgroups/v1/services.proto

package sgroupsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SGroupsNamespaceAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsNamespaceAPI/Upsert"
	SGroupsNamespaceAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsNamespaceAPI/Delete"
	SGroupsNamespaceAPI_List_FullMethodName   = "/sgroups.v1.SGroupsNamespaceAPI/List"
	SGroupsNamespaceAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsNamespaceAPI/Watch"
)

// SGroupsNamespaceAPIClient is the client API for SGroupsNamespaceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsNamespaceAPI: SGroups namespaces API
type SGroupsNamespaceAPIClient interface {
	// Upsert: Create or update namespace(es)
	Upsert(ctx context.Context, in *NamespaceReq_Upsert, opts ...grpc.CallOption) (*NamespaceResp_Upsert, error)
	// Delete: Delete namespace(es)
	Delete(ctx context.Context, in *NamespaceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List namespace(es)
	List(ctx context.Context, in *NamespaceReq_List, opts ...grpc.CallOption) (*NamespaceResp_List, error)
	// Watch: Watch namespace(es)
	Watch(ctx context.Context, in *NamespaceReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NamespaceResp_Watch], error)
}

type sGroupsNamespaceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsNamespaceAPIClient(cc grpc.ClientConnInterface) SGroupsNamespaceAPIClient {
	return &sGroupsNamespaceAPIClient{cc}
}

func (c *sGroupsNamespaceAPIClient) Upsert(ctx context.Context, in *NamespaceReq_Upsert, opts ...grpc.CallOption) (*NamespaceResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) Delete(ctx context.Context, in *NamespaceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) List(ctx context.Context, in *NamespaceReq_List, opts ...grpc.CallOption) (*NamespaceResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResp_List)
	err := c.cc.Invoke(ctx, SGroupsNamespaceAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNamespaceAPIClient) Watch(ctx context.Context, in *NamespaceReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NamespaceResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsNamespaceAPI_ServiceDesc.Streams[0], SGroupsNamespaceAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NamespaceReq_Watch, NamespaceResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNamespaceAPI_WatchClient = grpc.ServerStreamingClient[NamespaceResp_Watch]

// SGroupsNamespaceAPIServer is the server API for SGroupsNamespaceAPI service.
// All implementations must embed UnimplementedSGroupsNamespaceAPIServer
// for forward compatibility.
//
// SGroupsNamespaceAPI: SGroups namespaces API
type SGroupsNamespaceAPIServer interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *NamespaceReq_Upsert) (*NamespaceResp_Upsert, error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *NamespaceReq_Delete) (*emptypb.Empty, error)
	// List: List namespace(es)
	List(context.Context, *NamespaceReq_List) (*NamespaceResp_List, error)
	// Watch: Watch namespace(es)
	Watch(*NamespaceReq_Watch, grpc.ServerStreamingServer[NamespaceResp_Watch]) error
	mustEmbedUnimplementedSGroupsNamespaceAPIServer()
}

// UnimplementedSGroupsNamespaceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsNamespaceAPIServer struct{}

func (UnimplementedSGroupsNamespaceAPIServer) Upsert(context.Context, *NamespaceReq_Upsert) (*NamespaceResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) Delete(context.Context, *NamespaceReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) List(context.Context, *NamespaceReq_List) (*NamespaceResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) Watch(*NamespaceReq_Watch, grpc.ServerStreamingServer[NamespaceResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsNamespaceAPIServer) mustEmbedUnimplementedSGroupsNamespaceAPIServer() {}
func (UnimplementedSGroupsNamespaceAPIServer) testEmbeddedByValue()                             {}

// UnsafeSGroupsNamespaceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsNamespaceAPIServer will
// result in compilation errors.
type UnsafeSGroupsNamespaceAPIServer interface {
	mustEmbedUnimplementedSGroupsNamespaceAPIServer()
}

func RegisterSGroupsNamespaceAPIServer(s grpc.ServiceRegistrar, srv SGroupsNamespaceAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsNamespaceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsNamespaceAPI_ServiceDesc, srv)
}

func _SGroupsNamespaceAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Upsert(ctx, req.(*NamespaceReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).Delete(ctx, req.(*NamespaceReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNamespaceAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNamespaceAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNamespaceAPIServer).List(ctx, req.(*NamespaceReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNamespaceAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamespaceReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsNamespaceAPIServer).Watch(m, &grpc.GenericServerStream[NamespaceReq_Watch, NamespaceResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNamespaceAPI_WatchServer = grpc.ServerStreamingServer[NamespaceResp_Watch]

// SGroupsNamespaceAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsNamespaceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsNamespaceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsNamespaceAPI",
	HandlerType: (*SGroupsNamespaceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsNamespaceAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsNamespaceAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsNamespaceAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsNamespaceAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsAddressGroupsAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsAddressGroupsAPI/Upsert"
	SGroupsAddressGroupsAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsAddressGroupsAPI/Delete"
	SGroupsAddressGroupsAPI_List_FullMethodName   = "/sgroups.v1.SGroupsAddressGroupsAPI/List"
	SGroupsAddressGroupsAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsAddressGroupsAPI/Watch"
)

// SGroupsAddressGroupsAPIClient is the client API for SGroupsAddressGroupsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsAddressGroupsAPI: SGroups AddressGroups API
type SGroupsAddressGroupsAPIClient interface {
	// Upsert: Create or update address group(s)
	Upsert(ctx context.Context, in *AddressGroupReq_Upsert, opts ...grpc.CallOption) (*AddressGroupResp_Upsert, error)
	// Delete: Delete address group(s)
	Delete(ctx context.Context, in *AddressGroupReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List address group(s)
	List(ctx context.Context, in *AddressGroupReq_List, opts ...grpc.CallOption) (*AddressGroupResp_List, error)
	// Watch: Watch address group(s)
	Watch(ctx context.Context, in *AddressGroupReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AddressGroupResp_Watch], error)
}

type sGroupsAddressGroupsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsAddressGroupsAPIClient(cc grpc.ClientConnInterface) SGroupsAddressGroupsAPIClient {
	return &sGroupsAddressGroupsAPIClient{cc}
}

func (c *sGroupsAddressGroupsAPIClient) Upsert(ctx context.Context, in *AddressGroupReq_Upsert, opts ...grpc.CallOption) (*AddressGroupResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) Delete(ctx context.Context, in *AddressGroupReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) List(ctx context.Context, in *AddressGroupReq_List, opts ...grpc.CallOption) (*AddressGroupResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressGroupResp_List)
	err := c.cc.Invoke(ctx, SGroupsAddressGroupsAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsAddressGroupsAPIClient) Watch(ctx context.Context, in *AddressGroupReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AddressGroupResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsAddressGroupsAPI_ServiceDesc.Streams[0], SGroupsAddressGroupsAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddressGroupReq_Watch, AddressGroupResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsAddressGroupsAPI_WatchClient = grpc.ServerStreamingClient[AddressGroupResp_Watch]

// SGroupsAddressGroupsAPIServer is the server API for SGroupsAddressGroupsAPI service.
// All implementations must embed UnimplementedSGroupsAddressGroupsAPIServer
// for forward compatibility.
//
// SGroupsAddressGroupsAPI: SGroups AddressGroups API
type SGroupsAddressGroupsAPIServer interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *AddressGroupReq_Upsert) (*AddressGroupResp_Upsert, error)
	// Delete: Delete address group(s)
	Delete(context.Context, *AddressGroupReq_Delete) (*emptypb.Empty, error)
	// List: List address group(s)
	List(context.Context, *AddressGroupReq_List) (*AddressGroupResp_List, error)
	// Watch: Watch address group(s)
	Watch(*AddressGroupReq_Watch, grpc.ServerStreamingServer[AddressGroupResp_Watch]) error
	mustEmbedUnimplementedSGroupsAddressGroupsAPIServer()
}

// UnimplementedSGroupsAddressGroupsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsAddressGroupsAPIServer struct{}

func (UnimplementedSGroupsAddressGroupsAPIServer) Upsert(context.Context, *AddressGroupReq_Upsert) (*AddressGroupResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) Delete(context.Context, *AddressGroupReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) List(context.Context, *AddressGroupReq_List) (*AddressGroupResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) Watch(*AddressGroupReq_Watch, grpc.ServerStreamingServer[AddressGroupResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsAddressGroupsAPIServer) mustEmbedUnimplementedSGroupsAddressGroupsAPIServer() {
}
func (UnimplementedSGroupsAddressGroupsAPIServer) testEmbeddedByValue() {}

// UnsafeSGroupsAddressGroupsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsAddressGroupsAPIServer will
// result in compilation errors.
type UnsafeSGroupsAddressGroupsAPIServer interface {
	mustEmbedUnimplementedSGroupsAddressGroupsAPIServer()
}

func RegisterSGroupsAddressGroupsAPIServer(s grpc.ServiceRegistrar, srv SGroupsAddressGroupsAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsAddressGroupsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsAddressGroupsAPI_ServiceDesc, srv)
}

func _SGroupsAddressGroupsAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Upsert(ctx, req.(*AddressGroupReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).Delete(ctx, req.(*AddressGroupReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGroupReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsAddressGroupsAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsAddressGroupsAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsAddressGroupsAPIServer).List(ctx, req.(*AddressGroupReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsAddressGroupsAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddressGroupReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsAddressGroupsAPIServer).Watch(m, &grpc.GenericServerStream[AddressGroupReq_Watch, AddressGroupResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsAddressGroupsAPI_WatchServer = grpc.ServerStreamingServer[AddressGroupResp_Watch]

// SGroupsAddressGroupsAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsAddressGroupsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsAddressGroupsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsAddressGroupsAPI",
	HandlerType: (*SGroupsAddressGroupsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsAddressGroupsAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsAddressGroupsAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsAddressGroupsAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsAddressGroupsAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsNetworksAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsNetworksAPI/Upsert"
	SGroupsNetworksAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsNetworksAPI/Delete"
	SGroupsNetworksAPI_List_FullMethodName   = "/sgroups.v1.SGroupsNetworksAPI/List"
	SGroupsNetworksAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsNetworksAPI/Watch"
)

// SGroupsNetworksAPIClient is the client API for SGroupsNetworksAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsNetworksAPI: SGroups Networks API
type SGroupsNetworksAPIClient interface {
	// Upsert: Create or update network(s)
	Upsert(ctx context.Context, in *NetworkReq_Upsert, opts ...grpc.CallOption) (*NetworkResp_Upsert, error)
	// Delete: Delete network(s)
	Delete(ctx context.Context, in *NetworkReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List network(s)
	List(ctx context.Context, in *NetworkReq_List, opts ...grpc.CallOption) (*NetworkResp_List, error)
	// Watch: Watch network(s)
	Watch(ctx context.Context, in *NetworkReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkResp_Watch], error)
}

type sGroupsNetworksAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsNetworksAPIClient(cc grpc.ClientConnInterface) SGroupsNetworksAPIClient {
	return &sGroupsNetworksAPIClient{cc}
}

func (c *sGroupsNetworksAPIClient) Upsert(ctx context.Context, in *NetworkReq_Upsert, opts ...grpc.CallOption) (*NetworkResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsNetworksAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNetworksAPIClient) Delete(ctx context.Context, in *NetworkReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsNetworksAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNetworksAPIClient) List(ctx context.Context, in *NetworkReq_List, opts ...grpc.CallOption) (*NetworkResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkResp_List)
	err := c.cc.Invoke(ctx, SGroupsNetworksAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNetworksAPIClient) Watch(ctx context.Context, in *NetworkReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsNetworksAPI_ServiceDesc.Streams[0], SGroupsNetworksAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NetworkReq_Watch, NetworkResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNetworksAPI_WatchClient = grpc.ServerStreamingClient[NetworkResp_Watch]

// SGroupsNetworksAPIServer is the server API for SGroupsNetworksAPI service.
// All implementations must embed UnimplementedSGroupsNetworksAPIServer
// for forward compatibility.
//
// SGroupsNetworksAPI: SGroups Networks API
type SGroupsNetworksAPIServer interface {
	// Upsert: Create or update network(s)
	Upsert(context.Context, *NetworkReq_Upsert) (*NetworkResp_Upsert, error)
	// Delete: Delete network(s)
	Delete(context.Context, *NetworkReq_Delete) (*emptypb.Empty, error)
	// List: List network(s)
	List(context.Context, *NetworkReq_List) (*NetworkResp_List, error)
	// Watch: Watch network(s)
	Watch(*NetworkReq_Watch, grpc.ServerStreamingServer[NetworkResp_Watch]) error
	mustEmbedUnimplementedSGroupsNetworksAPIServer()
}

// UnimplementedSGroupsNetworksAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsNetworksAPIServer struct{}

func (UnimplementedSGroupsNetworksAPIServer) Upsert(context.Context, *NetworkReq_Upsert) (*NetworkResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsNetworksAPIServer) Delete(context.Context, *NetworkReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsNetworksAPIServer) List(context.Context, *NetworkReq_List) (*NetworkResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsNetworksAPIServer) Watch(*NetworkReq_Watch, grpc.ServerStreamingServer[NetworkResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsNetworksAPIServer) mustEmbedUnimplementedSGroupsNetworksAPIServer() {}
func (UnimplementedSGroupsNetworksAPIServer) testEmbeddedByValue()                            {}

// UnsafeSGroupsNetworksAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsNetworksAPIServer will
// result in compilation errors.
type UnsafeSGroupsNetworksAPIServer interface {
	mustEmbedUnimplementedSGroupsNetworksAPIServer()
}

func RegisterSGroupsNetworksAPIServer(s grpc.ServiceRegistrar, srv SGroupsNetworksAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsNetworksAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsNetworksAPI_ServiceDesc, srv)
}

func _SGroupsNetworksAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNetworksAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNetworksAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNetworksAPIServer).Upsert(ctx, req.(*NetworkReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNetworksAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNetworksAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNetworksAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNetworksAPIServer).Delete(ctx, req.(*NetworkReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNetworksAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNetworksAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNetworksAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNetworksAPIServer).List(ctx, req.(*NetworkReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNetworksAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NetworkReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsNetworksAPIServer).Watch(m, &grpc.GenericServerStream[NetworkReq_Watch, NetworkResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNetworksAPI_WatchServer = grpc.ServerStreamingServer[NetworkResp_Watch]

// SGroupsNetworksAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsNetworksAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsNetworksAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsNetworksAPI",
	HandlerType: (*SGroupsNetworksAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsNetworksAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsNetworksAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsNetworksAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsNetworksAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsHostsAPI_Upsert_FullMethodName      = "/sgroups.v1.SGroupsHostsAPI/Upsert"
	SGroupsHostsAPI_Delete_FullMethodName      = "/sgroups.v1.SGroupsHostsAPI/Delete"
	SGroupsHostsAPI_List_FullMethodName        = "/sgroups.v1.SGroupsHostsAPI/List"
	SGroupsHostsAPI_Watch_FullMethodName       = "/sgroups.v1.SGroupsHostsAPI/Watch"
	SGroupsHostsAPI_UpdIPs_FullMethodName      = "/sgroups.v1.SGroupsHostsAPI/UpdIPs"
	SGroupsHostsAPI_UpdMetaInfo_FullMethodName = "/sgroups.v1.SGroupsHostsAPI/UpdMetaInfo"
)

// SGroupsHostsAPIClient is the client API for SGroupsHostsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsHostsAPI: SGroups Hosts API
type SGroupsHostsAPIClient interface {
	// Upsert: Create or update host(s)
	Upsert(ctx context.Context, in *HostReq_Upsert, opts ...grpc.CallOption) (*HostResp_Upsert, error)
	// Delete: Delete host(s)
	Delete(ctx context.Context, in *HostReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List host(s)
	List(ctx context.Context, in *HostReq_List, opts ...grpc.CallOption) (*HostResp_List, error)
	// Watch: Watch host(s)
	Watch(ctx context.Context, in *HostReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostResp_Watch], error)
	// UpdIPs: Update host(s) IPs
	UpdIPs(ctx context.Context, in *HostReq_UpdIPs, opts ...grpc.CallOption) (*HostResp_UpdIPs, error)
	// UpdMetaInfo: Update host(s) meta information
	UpdMetaInfo(ctx context.Context, in *HostReq_UpdMetaInfo, opts ...grpc.CallOption) (*HostResp_UpdMetaInfo, error)
}

type sGroupsHostsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsHostsAPIClient(cc grpc.ClientConnInterface) SGroupsHostsAPIClient {
	return &sGroupsHostsAPIClient{cc}
}

func (c *sGroupsHostsAPIClient) Upsert(ctx context.Context, in *HostReq_Upsert, opts ...grpc.CallOption) (*HostResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) Delete(ctx context.Context, in *HostReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) List(ctx context.Context, in *HostReq_List, opts ...grpc.CallOption) (*HostResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_List)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) Watch(ctx context.Context, in *HostReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsHostsAPI_ServiceDesc.Streams[0], SGroupsHostsAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostReq_Watch, HostResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsHostsAPI_WatchClient = grpc.ServerStreamingClient[HostResp_Watch]

func (c *sGroupsHostsAPIClient) UpdIPs(ctx context.Context, in *HostReq_UpdIPs, opts ...grpc.CallOption) (*HostResp_UpdIPs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_UpdIPs)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_UpdIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostsAPIClient) UpdMetaInfo(ctx context.Context, in *HostReq_UpdMetaInfo, opts ...grpc.CallOption) (*HostResp_UpdMetaInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResp_UpdMetaInfo)
	err := c.cc.Invoke(ctx, SGroupsHostsAPI_UpdMetaInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SGroupsHostsAPIServer is the server API for SGroupsHostsAPI service.
// All implementations must embed UnimplementedSGroupsHostsAPIServer
// for forward compatibility.
//
// SGroupsHostsAPI: SGroups Hosts API
type SGroupsHostsAPIServer interface {
	// Upsert: Create or update host(s)
	Upsert(context.Context, *HostReq_Upsert) (*HostResp_Upsert, error)
	// Delete: Delete host(s)
	Delete(context.Context, *HostReq_Delete) (*emptypb.Empty, error)
	// List: List host(s)
	List(context.Context, *HostReq_List) (*HostResp_List, error)
	// Watch: Watch host(s)
	Watch(*HostReq_Watch, grpc.ServerStreamingServer[HostResp_Watch]) error
	// UpdIPs: Update host(s) IPs
	UpdIPs(context.Context, *HostReq_UpdIPs) (*HostResp_UpdIPs, error)
	// UpdMetaInfo: Update host(s) meta information
	UpdMetaInfo(context.Context, *HostReq_UpdMetaInfo) (*HostResp_UpdMetaInfo, error)
	mustEmbedUnimplementedSGroupsHostsAPIServer()
}

// UnimplementedSGroupsHostsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsHostsAPIServer struct{}

func (UnimplementedSGroupsHostsAPIServer) Upsert(context.Context, *HostReq_Upsert) (*HostResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) Delete(context.Context, *HostReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) List(context.Context, *HostReq_List) (*HostResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) Watch(*HostReq_Watch, grpc.ServerStreamingServer[HostResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) UpdIPs(context.Context, *HostReq_UpdIPs) (*HostResp_UpdIPs, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdIPs not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) UpdMetaInfo(context.Context, *HostReq_UpdMetaInfo) (*HostResp_UpdMetaInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdMetaInfo not implemented")
}
func (UnimplementedSGroupsHostsAPIServer) mustEmbedUnimplementedSGroupsHostsAPIServer() {}
func (UnimplementedSGroupsHostsAPIServer) testEmbeddedByValue()                         {}

// UnsafeSGroupsHostsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsHostsAPIServer will
// result in compilation errors.
type UnsafeSGroupsHostsAPIServer interface {
	mustEmbedUnimplementedSGroupsHostsAPIServer()
}

func RegisterSGroupsHostsAPIServer(s grpc.ServiceRegistrar, srv SGroupsHostsAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsHostsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsHostsAPI_ServiceDesc, srv)
}

func _SGroupsHostsAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).Upsert(ctx, req.(*HostReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).Delete(ctx, req.(*HostReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).List(ctx, req.(*HostReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HostReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsHostsAPIServer).Watch(m, &grpc.GenericServerStream[HostReq_Watch, HostResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsHostsAPI_WatchServer = grpc.ServerStreamingServer[HostResp_Watch]

func _SGroupsHostsAPI_UpdIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_UpdIPs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).UpdIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_UpdIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).UpdIPs(ctx, req.(*HostReq_UpdIPs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostsAPI_UpdMetaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReq_UpdMetaInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostsAPIServer).UpdMetaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostsAPI_UpdMetaInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostsAPIServer).UpdMetaInfo(ctx, req.(*HostReq_UpdMetaInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// SGroupsHostsAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsHostsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsHostsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsHostsAPI",
	HandlerType: (*SGroupsHostsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsHostsAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsHostsAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsHostsAPI_List_Handler,
		},
		{
			MethodName: "UpdIPs",
			Handler:    _SGroupsHostsAPI_UpdIPs_Handler,
		},
		{
			MethodName: "UpdMetaInfo",
			Handler:    _SGroupsHostsAPI_UpdMetaInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsHostsAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsHostBindingAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsHostBindingAPI/Upsert"
	SGroupsHostBindingAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsHostBindingAPI/Delete"
	SGroupsHostBindingAPI_List_FullMethodName   = "/sgroups.v1.SGroupsHostBindingAPI/List"
	SGroupsHostBindingAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsHostBindingAPI/Watch"
)

// SGroupsHostBindingAPIClient is the client API for SGroupsHostBindingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsHostBindingAPI: SGroups Host Binding API
type SGroupsHostBindingAPIClient interface {
	// Upsert: Create or update host binding(s)
	Upsert(ctx context.Context, in *HostBindingReq_Upsert, opts ...grpc.CallOption) (*HostBindingResp_Upsert, error)
	// Delete: Delete host binding(s)
	Delete(ctx context.Context, in *HostBindingReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List host binding(s)
	List(ctx context.Context, in *HostBindingReq_List, opts ...grpc.CallOption) (*HostBindingResp_List, error)
	// Watch: Watch host binding(s)
	Watch(ctx context.Context, in *HostBindingReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostBindingResp_Watch], error)
}

type sGroupsHostBindingAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsHostBindingAPIClient(cc grpc.ClientConnInterface) SGroupsHostBindingAPIClient {
	return &sGroupsHostBindingAPIClient{cc}
}

func (c *sGroupsHostBindingAPIClient) Upsert(ctx context.Context, in *HostBindingReq_Upsert, opts ...grpc.CallOption) (*HostBindingResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostBindingResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsHostBindingAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostBindingAPIClient) Delete(ctx context.Context, in *HostBindingReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsHostBindingAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostBindingAPIClient) List(ctx context.Context, in *HostBindingReq_List, opts ...grpc.CallOption) (*HostBindingResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostBindingResp_List)
	err := c.cc.Invoke(ctx, SGroupsHostBindingAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsHostBindingAPIClient) Watch(ctx context.Context, in *HostBindingReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostBindingResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsHostBindingAPI_ServiceDesc.Streams[0], SGroupsHostBindingAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostBindingReq_Watch, HostBindingResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsHostBindingAPI_WatchClient = grpc.ServerStreamingClient[HostBindingResp_Watch]

// SGroupsHostBindingAPIServer is the server API for SGroupsHostBindingAPI service.
// All implementations must embed UnimplementedSGroupsHostBindingAPIServer
// for forward compatibility.
//
// SGroupsHostBindingAPI: SGroups Host Binding API
type SGroupsHostBindingAPIServer interface {
	// Upsert: Create or update host binding(s)
	Upsert(context.Context, *HostBindingReq_Upsert) (*HostBindingResp_Upsert, error)
	// Delete: Delete host binding(s)
	Delete(context.Context, *HostBindingReq_Delete) (*emptypb.Empty, error)
	// List: List host binding(s)
	List(context.Context, *HostBindingReq_List) (*HostBindingResp_List, error)
	// Watch: Watch host binding(s)
	Watch(*HostBindingReq_Watch, grpc.ServerStreamingServer[HostBindingResp_Watch]) error
	mustEmbedUnimplementedSGroupsHostBindingAPIServer()
}

// UnimplementedSGroupsHostBindingAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsHostBindingAPIServer struct{}

func (UnimplementedSGroupsHostBindingAPIServer) Upsert(context.Context, *HostBindingReq_Upsert) (*HostBindingResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsHostBindingAPIServer) Delete(context.Context, *HostBindingReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsHostBindingAPIServer) List(context.Context, *HostBindingReq_List) (*HostBindingResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsHostBindingAPIServer) Watch(*HostBindingReq_Watch, grpc.ServerStreamingServer[HostBindingResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsHostBindingAPIServer) mustEmbedUnimplementedSGroupsHostBindingAPIServer() {}
func (UnimplementedSGroupsHostBindingAPIServer) testEmbeddedByValue()                               {}

// UnsafeSGroupsHostBindingAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsHostBindingAPIServer will
// result in compilation errors.
type UnsafeSGroupsHostBindingAPIServer interface {
	mustEmbedUnimplementedSGroupsHostBindingAPIServer()
}

func RegisterSGroupsHostBindingAPIServer(s grpc.ServiceRegistrar, srv SGroupsHostBindingAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsHostBindingAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsHostBindingAPI_ServiceDesc, srv)
}

func _SGroupsHostBindingAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBindingReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostBindingAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostBindingAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostBindingAPIServer).Upsert(ctx, req.(*HostBindingReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostBindingAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBindingReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostBindingAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostBindingAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostBindingAPIServer).Delete(ctx, req.(*HostBindingReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostBindingAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBindingReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsHostBindingAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsHostBindingAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsHostBindingAPIServer).List(ctx, req.(*HostBindingReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsHostBindingAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HostBindingReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsHostBindingAPIServer).Watch(m, &grpc.GenericServerStream[HostBindingReq_Watch, HostBindingResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsHostBindingAPI_WatchServer = grpc.ServerStreamingServer[HostBindingResp_Watch]

// SGroupsHostBindingAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsHostBindingAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsHostBindingAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsHostBindingAPI",
	HandlerType: (*SGroupsHostBindingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsHostBindingAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsHostBindingAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsHostBindingAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsHostBindingAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsNetworkBindingAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsNetworkBindingAPI/Upsert"
	SGroupsNetworkBindingAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsNetworkBindingAPI/Delete"
	SGroupsNetworkBindingAPI_List_FullMethodName   = "/sgroups.v1.SGroupsNetworkBindingAPI/List"
	SGroupsNetworkBindingAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsNetworkBindingAPI/Watch"
)

// SGroupsNetworkBindingAPIClient is the client API for SGroupsNetworkBindingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsNetworkBindingAPI: SGroups Network Binding API
type SGroupsNetworkBindingAPIClient interface {
	// Upsert: Create or update network binding(s)
	Upsert(ctx context.Context, in *NetworkBindingReq_Upsert, opts ...grpc.CallOption) (*NetworkBindingResp_Upsert, error)
	// Delete: Delete network binding(s)
	Delete(ctx context.Context, in *NetworkBindingReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List network binding(s)
	List(ctx context.Context, in *NetworkBindingReq_List, opts ...grpc.CallOption) (*NetworkBindingResp_List, error)
	// Watch: Watch network binding(s)
	Watch(ctx context.Context, in *NetworkBindingReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkBindingResp_Watch], error)
}

type sGroupsNetworkBindingAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsNetworkBindingAPIClient(cc grpc.ClientConnInterface) SGroupsNetworkBindingAPIClient {
	return &sGroupsNetworkBindingAPIClient{cc}
}

func (c *sGroupsNetworkBindingAPIClient) Upsert(ctx context.Context, in *NetworkBindingReq_Upsert, opts ...grpc.CallOption) (*NetworkBindingResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkBindingResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsNetworkBindingAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNetworkBindingAPIClient) Delete(ctx context.Context, in *NetworkBindingReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsNetworkBindingAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNetworkBindingAPIClient) List(ctx context.Context, in *NetworkBindingReq_List, opts ...grpc.CallOption) (*NetworkBindingResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkBindingResp_List)
	err := c.cc.Invoke(ctx, SGroupsNetworkBindingAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsNetworkBindingAPIClient) Watch(ctx context.Context, in *NetworkBindingReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkBindingResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsNetworkBindingAPI_ServiceDesc.Streams[0], SGroupsNetworkBindingAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NetworkBindingReq_Watch, NetworkBindingResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNetworkBindingAPI_WatchClient = grpc.ServerStreamingClient[NetworkBindingResp_Watch]

// SGroupsNetworkBindingAPIServer is the server API for SGroupsNetworkBindingAPI service.
// All implementations must embed UnimplementedSGroupsNetworkBindingAPIServer
// for forward compatibility.
//
// SGroupsNetworkBindingAPI: SGroups Network Binding API
type SGroupsNetworkBindingAPIServer interface {
	// Upsert: Create or update network binding(s)
	Upsert(context.Context, *NetworkBindingReq_Upsert) (*NetworkBindingResp_Upsert, error)
	// Delete: Delete network binding(s)
	Delete(context.Context, *NetworkBindingReq_Delete) (*emptypb.Empty, error)
	// List: List network binding(s)
	List(context.Context, *NetworkBindingReq_List) (*NetworkBindingResp_List, error)
	// Watch: Watch network binding(s)
	Watch(*NetworkBindingReq_Watch, grpc.ServerStreamingServer[NetworkBindingResp_Watch]) error
	mustEmbedUnimplementedSGroupsNetworkBindingAPIServer()
}

// UnimplementedSGroupsNetworkBindingAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsNetworkBindingAPIServer struct{}

func (UnimplementedSGroupsNetworkBindingAPIServer) Upsert(context.Context, *NetworkBindingReq_Upsert) (*NetworkBindingResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsNetworkBindingAPIServer) Delete(context.Context, *NetworkBindingReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsNetworkBindingAPIServer) List(context.Context, *NetworkBindingReq_List) (*NetworkBindingResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsNetworkBindingAPIServer) Watch(*NetworkBindingReq_Watch, grpc.ServerStreamingServer[NetworkBindingResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsNetworkBindingAPIServer) mustEmbedUnimplementedSGroupsNetworkBindingAPIServer() {
}
func (UnimplementedSGroupsNetworkBindingAPIServer) testEmbeddedByValue() {}

// UnsafeSGroupsNetworkBindingAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsNetworkBindingAPIServer will
// result in compilation errors.
type UnsafeSGroupsNetworkBindingAPIServer interface {
	mustEmbedUnimplementedSGroupsNetworkBindingAPIServer()
}

func RegisterSGroupsNetworkBindingAPIServer(s grpc.ServiceRegistrar, srv SGroupsNetworkBindingAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsNetworkBindingAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsNetworkBindingAPI_ServiceDesc, srv)
}

func _SGroupsNetworkBindingAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkBindingReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNetworkBindingAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNetworkBindingAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNetworkBindingAPIServer).Upsert(ctx, req.(*NetworkBindingReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNetworkBindingAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkBindingReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNetworkBindingAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNetworkBindingAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNetworkBindingAPIServer).Delete(ctx, req.(*NetworkBindingReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNetworkBindingAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkBindingReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsNetworkBindingAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsNetworkBindingAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsNetworkBindingAPIServer).List(ctx, req.(*NetworkBindingReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsNetworkBindingAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NetworkBindingReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsNetworkBindingAPIServer).Watch(m, &grpc.GenericServerStream[NetworkBindingReq_Watch, NetworkBindingResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsNetworkBindingAPI_WatchServer = grpc.ServerStreamingServer[NetworkBindingResp_Watch]

// SGroupsNetworkBindingAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsNetworkBindingAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsNetworkBindingAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsNetworkBindingAPI",
	HandlerType: (*SGroupsNetworkBindingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsNetworkBindingAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsNetworkBindingAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsNetworkBindingAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsNetworkBindingAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsServicesAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsServicesAPI/Upsert"
	SGroupsServicesAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsServicesAPI/Delete"
	SGroupsServicesAPI_List_FullMethodName   = "/sgroups.v1.SGroupsServicesAPI/List"
	SGroupsServicesAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsServicesAPI/Watch"
)

// SGroupsServicesAPIClient is the client API for SGroupsServicesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsServicesAPI: SGroups Services API
type SGroupsServicesAPIClient interface {
	// Upsert: Create or update service(s)
	Upsert(ctx context.Context, in *ServiceReq_Upsert, opts ...grpc.CallOption) (*ServiceResp_Upsert, error)
	// Delete: Delete service(s)
	Delete(ctx context.Context, in *ServiceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List service(s)
	List(ctx context.Context, in *ServiceReq_List, opts ...grpc.CallOption) (*ServiceResp_List, error)
	// Watch: Watch service(s)
	Watch(ctx context.Context, in *ServiceReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceResp_Watch], error)
}

type sGroupsServicesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsServicesAPIClient(cc grpc.ClientConnInterface) SGroupsServicesAPIClient {
	return &sGroupsServicesAPIClient{cc}
}

func (c *sGroupsServicesAPIClient) Upsert(ctx context.Context, in *ServiceReq_Upsert, opts ...grpc.CallOption) (*ServiceResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsServicesAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsServicesAPIClient) Delete(ctx context.Context, in *ServiceReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsServicesAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsServicesAPIClient) List(ctx context.Context, in *ServiceReq_List, opts ...grpc.CallOption) (*ServiceResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResp_List)
	err := c.cc.Invoke(ctx, SGroupsServicesAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsServicesAPIClient) Watch(ctx context.Context, in *ServiceReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsServicesAPI_ServiceDesc.Streams[0], SGroupsServicesAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceReq_Watch, ServiceResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsServicesAPI_WatchClient = grpc.ServerStreamingClient[ServiceResp_Watch]

// SGroupsServicesAPIServer is the server API for SGroupsServicesAPI service.
// All implementations must embed UnimplementedSGroupsServicesAPIServer
// for forward compatibility.
//
// SGroupsServicesAPI: SGroups Services API
type SGroupsServicesAPIServer interface {
	// Upsert: Create or update service(s)
	Upsert(context.Context, *ServiceReq_Upsert) (*ServiceResp_Upsert, error)
	// Delete: Delete service(s)
	Delete(context.Context, *ServiceReq_Delete) (*emptypb.Empty, error)
	// List: List service(s)
	List(context.Context, *ServiceReq_List) (*ServiceResp_List, error)
	// Watch: Watch service(s)
	Watch(*ServiceReq_Watch, grpc.ServerStreamingServer[ServiceResp_Watch]) error
	mustEmbedUnimplementedSGroupsServicesAPIServer()
}

// UnimplementedSGroupsServicesAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsServicesAPIServer struct{}

func (UnimplementedSGroupsServicesAPIServer) Upsert(context.Context, *ServiceReq_Upsert) (*ServiceResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsServicesAPIServer) Delete(context.Context, *ServiceReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsServicesAPIServer) List(context.Context, *ServiceReq_List) (*ServiceResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsServicesAPIServer) Watch(*ServiceReq_Watch, grpc.ServerStreamingServer[ServiceResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsServicesAPIServer) mustEmbedUnimplementedSGroupsServicesAPIServer() {}
func (UnimplementedSGroupsServicesAPIServer) testEmbeddedByValue()                            {}

// UnsafeSGroupsServicesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsServicesAPIServer will
// result in compilation errors.
type UnsafeSGroupsServicesAPIServer interface {
	mustEmbedUnimplementedSGroupsServicesAPIServer()
}

func RegisterSGroupsServicesAPIServer(s grpc.ServiceRegistrar, srv SGroupsServicesAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsServicesAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsServicesAPI_ServiceDesc, srv)
}

func _SGroupsServicesAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsServicesAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsServicesAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsServicesAPIServer).Upsert(ctx, req.(*ServiceReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsServicesAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsServicesAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsServicesAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsServicesAPIServer).Delete(ctx, req.(*ServiceReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsServicesAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsServicesAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsServicesAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsServicesAPIServer).List(ctx, req.(*ServiceReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsServicesAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsServicesAPIServer).Watch(m, &grpc.GenericServerStream[ServiceReq_Watch, ServiceResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsServicesAPI_WatchServer = grpc.ServerStreamingServer[ServiceResp_Watch]

// SGroupsServicesAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsServicesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsServicesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsServicesAPI",
	HandlerType: (*SGroupsServicesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsServicesAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsServicesAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsServicesAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsServicesAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsServiceBindingAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsServiceBindingAPI/Upsert"
	SGroupsServiceBindingAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsServiceBindingAPI/Delete"
	SGroupsServiceBindingAPI_List_FullMethodName   = "/sgroups.v1.SGroupsServiceBindingAPI/List"
	SGroupsServiceBindingAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsServiceBindingAPI/Watch"
)

// SGroupsServiceBindingAPIClient is the client API for SGroupsServiceBindingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsServiceBindingAPI: SGroups Service Binding API
type SGroupsServiceBindingAPIClient interface {
	// Upsert: Create or update service binding(s)
	Upsert(ctx context.Context, in *ServiceBindingReq_Upsert, opts ...grpc.CallOption) (*ServiceBindingResp_Upsert, error)
	// Delete: Delete service binding(s)
	Delete(ctx context.Context, in *ServiceBindingReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List service binding(s)
	List(ctx context.Context, in *ServiceBindingReq_List, opts ...grpc.CallOption) (*ServiceBindingResp_List, error)
	// Watch: Watch service binding(s)
	Watch(ctx context.Context, in *ServiceBindingReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceBindingResp_Watch], error)
}

type sGroupsServiceBindingAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsServiceBindingAPIClient(cc grpc.ClientConnInterface) SGroupsServiceBindingAPIClient {
	return &sGroupsServiceBindingAPIClient{cc}
}

func (c *sGroupsServiceBindingAPIClient) Upsert(ctx context.Context, in *ServiceBindingReq_Upsert, opts ...grpc.CallOption) (*ServiceBindingResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceBindingResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsServiceBindingAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsServiceBindingAPIClient) Delete(ctx context.Context, in *ServiceBindingReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsServiceBindingAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsServiceBindingAPIClient) List(ctx context.Context, in *ServiceBindingReq_List, opts ...grpc.CallOption) (*ServiceBindingResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceBindingResp_List)
	err := c.cc.Invoke(ctx, SGroupsServiceBindingAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsServiceBindingAPIClient) Watch(ctx context.Context, in *ServiceBindingReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceBindingResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsServiceBindingAPI_ServiceDesc.Streams[0], SGroupsServiceBindingAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceBindingReq_Watch, ServiceBindingResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsServiceBindingAPI_WatchClient = grpc.ServerStreamingClient[ServiceBindingResp_Watch]

// SGroupsServiceBindingAPIServer is the server API for SGroupsServiceBindingAPI service.
// All implementations must embed UnimplementedSGroupsServiceBindingAPIServer
// for forward compatibility.
//
// SGroupsServiceBindingAPI: SGroups Service Binding API
type SGroupsServiceBindingAPIServer interface {
	// Upsert: Create or update service binding(s)
	Upsert(context.Context, *ServiceBindingReq_Upsert) (*ServiceBindingResp_Upsert, error)
	// Delete: Delete service binding(s)
	Delete(context.Context, *ServiceBindingReq_Delete) (*emptypb.Empty, error)
	// List: List service binding(s)
	List(context.Context, *ServiceBindingReq_List) (*ServiceBindingResp_List, error)
	// Watch: Watch service binding(s)
	Watch(*ServiceBindingReq_Watch, grpc.ServerStreamingServer[ServiceBindingResp_Watch]) error
	mustEmbedUnimplementedSGroupsServiceBindingAPIServer()
}

// UnimplementedSGroupsServiceBindingAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsServiceBindingAPIServer struct{}

func (UnimplementedSGroupsServiceBindingAPIServer) Upsert(context.Context, *ServiceBindingReq_Upsert) (*ServiceBindingResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsServiceBindingAPIServer) Delete(context.Context, *ServiceBindingReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsServiceBindingAPIServer) List(context.Context, *ServiceBindingReq_List) (*ServiceBindingResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsServiceBindingAPIServer) Watch(*ServiceBindingReq_Watch, grpc.ServerStreamingServer[ServiceBindingResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsServiceBindingAPIServer) mustEmbedUnimplementedSGroupsServiceBindingAPIServer() {
}
func (UnimplementedSGroupsServiceBindingAPIServer) testEmbeddedByValue() {}

// UnsafeSGroupsServiceBindingAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsServiceBindingAPIServer will
// result in compilation errors.
type UnsafeSGroupsServiceBindingAPIServer interface {
	mustEmbedUnimplementedSGroupsServiceBindingAPIServer()
}

func RegisterSGroupsServiceBindingAPIServer(s grpc.ServiceRegistrar, srv SGroupsServiceBindingAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsServiceBindingAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsServiceBindingAPI_ServiceDesc, srv)
}

func _SGroupsServiceBindingAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceBindingReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsServiceBindingAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsServiceBindingAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsServiceBindingAPIServer).Upsert(ctx, req.(*ServiceBindingReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsServiceBindingAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceBindingReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsServiceBindingAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsServiceBindingAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsServiceBindingAPIServer).Delete(ctx, req.(*ServiceBindingReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsServiceBindingAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceBindingReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsServiceBindingAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsServiceBindingAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsServiceBindingAPIServer).List(ctx, req.(*ServiceBindingReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsServiceBindingAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceBindingReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsServiceBindingAPIServer).Watch(m, &grpc.GenericServerStream[ServiceBindingReq_Watch, ServiceBindingResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsServiceBindingAPI_WatchServer = grpc.ServerStreamingServer[ServiceBindingResp_Watch]

// SGroupsServiceBindingAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsServiceBindingAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsServiceBindingAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsServiceBindingAPI",
	HandlerType: (*SGroupsServiceBindingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsServiceBindingAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsServiceBindingAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsServiceBindingAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsServiceBindingAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsRulesAPI_Upsert_FullMethodName = "/sgroups.v1.SGroupsRulesAPI/Upsert"
	SGroupsRulesAPI_Delete_FullMethodName = "/sgroups.v1.SGroupsRulesAPI/Delete"
	SGroupsRulesAPI_List_FullMethodName   = "/sgroups.v1.SGroupsRulesAPI/List"
	SGroupsRulesAPI_Watch_FullMethodName  = "/sgroups.v1.SGroupsRulesAPI/Watch"
)

// SGroupsRulesAPIClient is the client API for SGroupsRulesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsRulesAPI: SGroups Rules API
type SGroupsRulesAPIClient interface {
	// Upsert: Create or update rules
	Upsert(ctx context.Context, in *RuleReq_Upsert, opts ...grpc.CallOption) (*RuleResp_Upsert, error)
	// Delete: Delete rules
	Delete(ctx context.Context, in *RuleReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List: List rules
	List(ctx context.Context, in *RuleReq_List, opts ...grpc.CallOption) (*RuleResp_List, error)
	// Watch: Watch rules
	Watch(ctx context.Context, in *RuleReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuleResp_Watch], error)
}

type sGroupsRulesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsRulesAPIClient(cc grpc.ClientConnInterface) SGroupsRulesAPIClient {
	return &sGroupsRulesAPIClient{cc}
}

func (c *sGroupsRulesAPIClient) Upsert(ctx context.Context, in *RuleReq_Upsert, opts ...grpc.CallOption) (*RuleResp_Upsert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleResp_Upsert)
	err := c.cc.Invoke(ctx, SGroupsRulesAPI_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsRulesAPIClient) Delete(ctx context.Context, in *RuleReq_Delete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SGroupsRulesAPI_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsRulesAPIClient) List(ctx context.Context, in *RuleReq_List, opts ...grpc.CallOption) (*RuleResp_List, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleResp_List)
	err := c.cc.Invoke(ctx, SGroupsRulesAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsRulesAPIClient) Watch(ctx context.Context, in *RuleReq_Watch, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuleResp_Watch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsRulesAPI_ServiceDesc.Streams[0], SGroupsRulesAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RuleReq_Watch, RuleResp_Watch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsRulesAPI_WatchClient = grpc.ServerStreamingClient[RuleResp_Watch]

// SGroupsRulesAPIServer is the server API for SGroupsRulesAPI service.
// All implementations must embed UnimplementedSGroupsRulesAPIServer
// for forward compatibility.
//
// SGroupsRulesAPI: SGroups Rules API
type SGroupsRulesAPIServer interface {
	// Upsert: Create or update rules
	Upsert(context.Context, *RuleReq_Upsert) (*RuleResp_Upsert, error)
	// Delete: Delete rules
	Delete(context.Context, *RuleReq_Delete) (*emptypb.Empty, error)
	// List: List rules
	List(context.Context, *RuleReq_List) (*RuleResp_List, error)
	// Watch: Watch rules
	Watch(*RuleReq_Watch, grpc.ServerStreamingServer[RuleResp_Watch]) error
	mustEmbedUnimplementedSGroupsRulesAPIServer()
}

// UnimplementedSGroupsRulesAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsRulesAPIServer struct{}

func (UnimplementedSGroupsRulesAPIServer) Upsert(context.Context, *RuleReq_Upsert) (*RuleResp_Upsert, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSGroupsRulesAPIServer) Delete(context.Context, *RuleReq_Delete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSGroupsRulesAPIServer) List(context.Context, *RuleReq_List) (*RuleResp_List, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsRulesAPIServer) Watch(*RuleReq_Watch, grpc.ServerStreamingServer[RuleResp_Watch]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsRulesAPIServer) mustEmbedUnimplementedSGroupsRulesAPIServer() {}
func (UnimplementedSGroupsRulesAPIServer) testEmbeddedByValue()                         {}

// UnsafeSGroupsRulesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsRulesAPIServer will
// result in compilation errors.
type UnsafeSGroupsRulesAPIServer interface {
	mustEmbedUnimplementedSGroupsRulesAPIServer()
}

func RegisterSGroupsRulesAPIServer(s grpc.ServiceRegistrar, srv SGroupsRulesAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsRulesAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsRulesAPI_ServiceDesc, srv)
}

func _SGroupsRulesAPI_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleReq_Upsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsRulesAPIServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsRulesAPI_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsRulesAPIServer).Upsert(ctx, req.(*RuleReq_Upsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsRulesAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleReq_Delete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsRulesAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsRulesAPI_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsRulesAPIServer).Delete(ctx, req.(*RuleReq_Delete))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsRulesAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleReq_List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsRulesAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsRulesAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsRulesAPIServer).List(ctx, req.(*RuleReq_List))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsRulesAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RuleReq_Watch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsRulesAPIServer).Watch(m, &grpc.GenericServerStream[RuleReq_Watch, RuleResp_Watch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsRulesAPI_WatchServer = grpc.ServerStreamingServer[RuleResp_Watch]

// SGroupsRulesAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsRulesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsRulesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsRulesAPI",
	HandlerType: (*SGroupsRulesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _SGroupsRulesAPI_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SGroupsRulesAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SGroupsRulesAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsRulesAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}

const (
	SGroupsStatusAPI_List_FullMethodName  = "/sgroups.v1.SGroupsStatusAPI/List"
	SGroupsStatusAPI_Watch_FullMethodName = "/sgroups.v1.SGroupsStatusAPI/Watch"
)

// SGroupsStatusAPIClient is the client API for SGroupsStatusAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SGroupsStatusAPI: SGroups Status API
type SGroupsStatusAPIClient interface {
	// List: gets last succeeded update DB status
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SyncStatusResp, error)
	// Watch: gets stream of update DB statuses
	Watch(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncStatusResp], error)
}

type sGroupsStatusAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSGroupsStatusAPIClient(cc grpc.ClientConnInterface) SGroupsStatusAPIClient {
	return &sGroupsStatusAPIClient{cc}
}

func (c *sGroupsStatusAPIClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SyncStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStatusResp)
	err := c.cc.Invoke(ctx, SGroupsStatusAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sGroupsStatusAPIClient) Watch(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncStatusResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SGroupsStatusAPI_ServiceDesc.Streams[0], SGroupsStatusAPI_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, SyncStatusResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsStatusAPI_WatchClient = grpc.ServerStreamingClient[SyncStatusResp]

// SGroupsStatusAPIServer is the server API for SGroupsStatusAPI service.
// All implementations must embed UnimplementedSGroupsStatusAPIServer
// for forward compatibility.
//
// SGroupsStatusAPI: SGroups Status API
type SGroupsStatusAPIServer interface {
	// List: gets last succeeded update DB status
	List(context.Context, *emptypb.Empty) (*SyncStatusResp, error)
	// Watch: gets stream of update DB statuses
	Watch(*emptypb.Empty, grpc.ServerStreamingServer[SyncStatusResp]) error
	mustEmbedUnimplementedSGroupsStatusAPIServer()
}

// UnimplementedSGroupsStatusAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSGroupsStatusAPIServer struct{}

func (UnimplementedSGroupsStatusAPIServer) List(context.Context, *emptypb.Empty) (*SyncStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSGroupsStatusAPIServer) Watch(*emptypb.Empty, grpc.ServerStreamingServer[SyncStatusResp]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSGroupsStatusAPIServer) mustEmbedUnimplementedSGroupsStatusAPIServer() {}
func (UnimplementedSGroupsStatusAPIServer) testEmbeddedByValue()                          {}

// UnsafeSGroupsStatusAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SGroupsStatusAPIServer will
// result in compilation errors.
type UnsafeSGroupsStatusAPIServer interface {
	mustEmbedUnimplementedSGroupsStatusAPIServer()
}

func RegisterSGroupsStatusAPIServer(s grpc.ServiceRegistrar, srv SGroupsStatusAPIServer) {
	// If the following call panics, it indicates UnimplementedSGroupsStatusAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SGroupsStatusAPI_ServiceDesc, srv)
}

func _SGroupsStatusAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SGroupsStatusAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SGroupsStatusAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SGroupsStatusAPIServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SGroupsStatusAPI_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SGroupsStatusAPIServer).Watch(m, &grpc.GenericServerStream[emptypb.Empty, SyncStatusResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SGroupsStatusAPI_WatchServer = grpc.ServerStreamingServer[SyncStatusResp]

// SGroupsStatusAPI_ServiceDesc is the grpc.ServiceDesc for SGroupsStatusAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SGroupsStatusAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgroups.v1.SGroupsStatusAPI",
	HandlerType: (*SGroupsStatusAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SGroupsStatusAPI_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SGroupsStatusAPI_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgroups/v1/services.proto",
}
