// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sgroups/v1/services.proto

package sgroupsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/PRO-Robotech/sgroups-proto/pkg/api/sgroups/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SGroupsNamespaceAPIName is the fully-qualified name of the SGroupsNamespaceAPI service.
	SGroupsNamespaceAPIName = "sgroups.v1.SGroupsNamespaceAPI"
	// SGroupsAddressGroupsAPIName is the fully-qualified name of the SGroupsAddressGroupsAPI service.
	SGroupsAddressGroupsAPIName = "sgroups.v1.SGroupsAddressGroupsAPI"
	// SGroupsNetworksAPIName is the fully-qualified name of the SGroupsNetworksAPI service.
	SGroupsNetworksAPIName = "sgroups.v1.SGroupsNetworksAPI"
	// SGroupsHostsAPIName is the fully-qualified name of the SGroupsHostsAPI service.
	SGroupsHostsAPIName = "sgroups.v1.SGroupsHostsAPI"
	// SGroupsHostBindingAPIName is the fully-qualified name of the SGroupsHostBindingAPI service.
	SGroupsHostBindingAPIName = "sgroups.v1.SGroupsHostBindingAPI"
	// SGroupsNetworkBindingAPIName is the fully-qualified name of the SGroupsNetworkBindingAPI service.
	SGroupsNetworkBindingAPIName = "sgroups.v1.SGroupsNetworkBindingAPI"
	// SGroupsServicesAPIName is the fully-qualified name of the SGroupsServicesAPI service.
	SGroupsServicesAPIName = "sgroups.v1.SGroupsServicesAPI"
	// SGroupsServiceBindingAPIName is the fully-qualified name of the SGroupsServiceBindingAPI service.
	SGroupsServiceBindingAPIName = "sgroups.v1.SGroupsServiceBindingAPI"
	// SGroupsRulesAPIName is the fully-qualified name of the SGroupsRulesAPI service.
	SGroupsRulesAPIName = "sgroups.v1.SGroupsRulesAPI"
	// SGroupsStatusAPIName is the fully-qualified name of the SGroupsStatusAPI service.
	SGroupsStatusAPIName = "sgroups.v1.SGroupsStatusAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SGroupsNamespaceAPIUpsertProcedure is the fully-qualified name of the SGroupsNamespaceAPI's
	// Upsert RPC.
	SGroupsNamespaceAPIUpsertProcedure = "/sgroups.v1.SGroupsNamespaceAPI/Upsert"
	// SGroupsNamespaceAPIDeleteProcedure is the fully-qualified name of the SGroupsNamespaceAPI's
	// Delete RPC.
	SGroupsNamespaceAPIDeleteProcedure = "/sgroups.v1.SGroupsNamespaceAPI/Delete"
	// SGroupsNamespaceAPIListProcedure is the fully-qualified name of the SGroupsNamespaceAPI's List
	// RPC.
	SGroupsNamespaceAPIListProcedure = "/sgroups.v1.SGroupsNamespaceAPI/List"
	// SGroupsNamespaceAPIWatchProcedure is the fully-qualified name of the SGroupsNamespaceAPI's Watch
	// RPC.
	SGroupsNamespaceAPIWatchProcedure = "/sgroups.v1.SGroupsNamespaceAPI/Watch"
	// SGroupsAddressGroupsAPIUpsertProcedure is the fully-qualified name of the
	// SGroupsAddressGroupsAPI's Upsert RPC.
	SGroupsAddressGroupsAPIUpsertProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/Upsert"
	// SGroupsAddressGroupsAPIDeleteProcedure is the fully-qualified name of the
	// SGroupsAddressGroupsAPI's Delete RPC.
	SGroupsAddressGroupsAPIDeleteProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/Delete"
	// SGroupsAddressGroupsAPIListProcedure is the fully-qualified name of the SGroupsAddressGroupsAPI's
	// List RPC.
	SGroupsAddressGroupsAPIListProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/List"
	// SGroupsAddressGroupsAPIWatchProcedure is the fully-qualified name of the
	// SGroupsAddressGroupsAPI's Watch RPC.
	SGroupsAddressGroupsAPIWatchProcedure = "/sgroups.v1.SGroupsAddressGroupsAPI/Watch"
	// SGroupsNetworksAPIUpsertProcedure is the fully-qualified name of the SGroupsNetworksAPI's Upsert
	// RPC.
	SGroupsNetworksAPIUpsertProcedure = "/sgroups.v1.SGroupsNetworksAPI/Upsert"
	// SGroupsNetworksAPIDeleteProcedure is the fully-qualified name of the SGroupsNetworksAPI's Delete
	// RPC.
	SGroupsNetworksAPIDeleteProcedure = "/sgroups.v1.SGroupsNetworksAPI/Delete"
	// SGroupsNetworksAPIListProcedure is the fully-qualified name of the SGroupsNetworksAPI's List RPC.
	SGroupsNetworksAPIListProcedure = "/sgroups.v1.SGroupsNetworksAPI/List"
	// SGroupsNetworksAPIWatchProcedure is the fully-qualified name of the SGroupsNetworksAPI's Watch
	// RPC.
	SGroupsNetworksAPIWatchProcedure = "/sgroups.v1.SGroupsNetworksAPI/Watch"
	// SGroupsHostsAPIUpsertProcedure is the fully-qualified name of the SGroupsHostsAPI's Upsert RPC.
	SGroupsHostsAPIUpsertProcedure = "/sgroups.v1.SGroupsHostsAPI/Upsert"
	// SGroupsHostsAPIDeleteProcedure is the fully-qualified name of the SGroupsHostsAPI's Delete RPC.
	SGroupsHostsAPIDeleteProcedure = "/sgroups.v1.SGroupsHostsAPI/Delete"
	// SGroupsHostsAPIListProcedure is the fully-qualified name of the SGroupsHostsAPI's List RPC.
	SGroupsHostsAPIListProcedure = "/sgroups.v1.SGroupsHostsAPI/List"
	// SGroupsHostsAPIWatchProcedure is the fully-qualified name of the SGroupsHostsAPI's Watch RPC.
	SGroupsHostsAPIWatchProcedure = "/sgroups.v1.SGroupsHostsAPI/Watch"
	// SGroupsHostsAPIUpdIPsProcedure is the fully-qualified name of the SGroupsHostsAPI's UpdIPs RPC.
	SGroupsHostsAPIUpdIPsProcedure = "/sgroups.v1.SGroupsHostsAPI/UpdIPs"
	// SGroupsHostsAPIUpdMetaInfoProcedure is the fully-qualified name of the SGroupsHostsAPI's
	// UpdMetaInfo RPC.
	SGroupsHostsAPIUpdMetaInfoProcedure = "/sgroups.v1.SGroupsHostsAPI/UpdMetaInfo"
	// SGroupsHostBindingAPIUpsertProcedure is the fully-qualified name of the SGroupsHostBindingAPI's
	// Upsert RPC.
	SGroupsHostBindingAPIUpsertProcedure = "/sgroups.v1.SGroupsHostBindingAPI/Upsert"
	// SGroupsHostBindingAPIDeleteProcedure is the fully-qualified name of the SGroupsHostBindingAPI's
	// Delete RPC.
	SGroupsHostBindingAPIDeleteProcedure = "/sgroups.v1.SGroupsHostBindingAPI/Delete"
	// SGroupsHostBindingAPIListProcedure is the fully-qualified name of the SGroupsHostBindingAPI's
	// List RPC.
	SGroupsHostBindingAPIListProcedure = "/sgroups.v1.SGroupsHostBindingAPI/List"
	// SGroupsHostBindingAPIWatchProcedure is the fully-qualified name of the SGroupsHostBindingAPI's
	// Watch RPC.
	SGroupsHostBindingAPIWatchProcedure = "/sgroups.v1.SGroupsHostBindingAPI/Watch"
	// SGroupsNetworkBindingAPIUpsertProcedure is the fully-qualified name of the
	// SGroupsNetworkBindingAPI's Upsert RPC.
	SGroupsNetworkBindingAPIUpsertProcedure = "/sgroups.v1.SGroupsNetworkBindingAPI/Upsert"
	// SGroupsNetworkBindingAPIDeleteProcedure is the fully-qualified name of the
	// SGroupsNetworkBindingAPI's Delete RPC.
	SGroupsNetworkBindingAPIDeleteProcedure = "/sgroups.v1.SGroupsNetworkBindingAPI/Delete"
	// SGroupsNetworkBindingAPIListProcedure is the fully-qualified name of the
	// SGroupsNetworkBindingAPI's List RPC.
	SGroupsNetworkBindingAPIListProcedure = "/sgroups.v1.SGroupsNetworkBindingAPI/List"
	// SGroupsNetworkBindingAPIWatchProcedure is the fully-qualified name of the
	// SGroupsNetworkBindingAPI's Watch RPC.
	SGroupsNetworkBindingAPIWatchProcedure = "/sgroups.v1.SGroupsNetworkBindingAPI/Watch"
	// SGroupsServicesAPIUpsertProcedure is the fully-qualified name of the SGroupsServicesAPI's Upsert
	// RPC.
	SGroupsServicesAPIUpsertProcedure = "/sgroups.v1.SGroupsServicesAPI/Upsert"
	// SGroupsServicesAPIDeleteProcedure is the fully-qualified name of the SGroupsServicesAPI's Delete
	// RPC.
	SGroupsServicesAPIDeleteProcedure = "/sgroups.v1.SGroupsServicesAPI/Delete"
	// SGroupsServicesAPIListProcedure is the fully-qualified name of the SGroupsServicesAPI's List RPC.
	SGroupsServicesAPIListProcedure = "/sgroups.v1.SGroupsServicesAPI/List"
	// SGroupsServicesAPIWatchProcedure is the fully-qualified name of the SGroupsServicesAPI's Watch
	// RPC.
	SGroupsServicesAPIWatchProcedure = "/sgroups.v1.SGroupsServicesAPI/Watch"
	// SGroupsServiceBindingAPIUpsertProcedure is the fully-qualified name of the
	// SGroupsServiceBindingAPI's Upsert RPC.
	SGroupsServiceBindingAPIUpsertProcedure = "/sgroups.v1.SGroupsServiceBindingAPI/Upsert"
	// SGroupsServiceBindingAPIDeleteProcedure is the fully-qualified name of the
	// SGroupsServiceBindingAPI's Delete RPC.
	SGroupsServiceBindingAPIDeleteProcedure = "/sgroups.v1.SGroupsServiceBindingAPI/Delete"
	// SGroupsServiceBindingAPIListProcedure is the fully-qualified name of the
	// SGroupsServiceBindingAPI's List RPC.
	SGroupsServiceBindingAPIListProcedure = "/sgroups.v1.SGroupsServiceBindingAPI/List"
	// SGroupsServiceBindingAPIWatchProcedure is the fully-qualified name of the
	// SGroupsServiceBindingAPI's Watch RPC.
	SGroupsServiceBindingAPIWatchProcedure = "/sgroups.v1.SGroupsServiceBindingAPI/Watch"
	// SGroupsRulesAPIUpsertProcedure is the fully-qualified name of the SGroupsRulesAPI's Upsert RPC.
	SGroupsRulesAPIUpsertProcedure = "/sgroups.v1.SGroupsRulesAPI/Upsert"
	// SGroupsRulesAPIDeleteProcedure is the fully-qualified name of the SGroupsRulesAPI's Delete RPC.
	SGroupsRulesAPIDeleteProcedure = "/sgroups.v1.SGroupsRulesAPI/Delete"
	// SGroupsRulesAPIListProcedure is the fully-qualified name of the SGroupsRulesAPI's List RPC.
	SGroupsRulesAPIListProcedure = "/sgroups.v1.SGroupsRulesAPI/List"
	// SGroupsRulesAPIWatchProcedure is the fully-qualified name of the SGroupsRulesAPI's Watch RPC.
	SGroupsRulesAPIWatchProcedure = "/sgroups.v1.SGroupsRulesAPI/Watch"
	// SGroupsStatusAPIListProcedure is the fully-qualified name of the SGroupsStatusAPI's List RPC.
	SGroupsStatusAPIListProcedure = "/sgroups.v1.SGroupsStatusAPI/List"
	// SGroupsStatusAPIWatchProcedure is the fully-qualified name of the SGroupsStatusAPI's Watch RPC.
	SGroupsStatusAPIWatchProcedure = "/sgroups.v1.SGroupsStatusAPI/Watch"
)

// SGroupsNamespaceAPIClient is a client for the sgroups.v1.SGroupsNamespaceAPI service.
type SGroupsNamespaceAPIClient interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceResp_Upsert], error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List namespace(es)
	List(context.Context, *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceResp_List], error)
	// Watch: Watch namespace(es)
	Watch(context.Context, *connect.Request[v1.NamespaceReq_Watch]) (*connect.ServerStreamForClient[v1.NamespaceResp_Watch], error)
}

// NewSGroupsNamespaceAPIClient constructs a client for the sgroups.v1.SGroupsNamespaceAPI service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsNamespaceAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsNamespaceAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsNamespaceAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNamespaceAPI").Methods()
	return &sGroupsNamespaceAPIClient{
		upsert: connect.NewClient[v1.NamespaceReq_Upsert, v1.NamespaceResp_Upsert](
			httpClient,
			baseURL+SGroupsNamespaceAPIUpsertProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.NamespaceReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsNamespaceAPIDeleteProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.NamespaceReq_List, v1.NamespaceResp_List](
			httpClient,
			baseURL+SGroupsNamespaceAPIListProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.NamespaceReq_Watch, v1.NamespaceResp_Watch](
			httpClient,
			baseURL+SGroupsNamespaceAPIWatchProcedure,
			connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsNamespaceAPIClient implements SGroupsNamespaceAPIClient.
type sGroupsNamespaceAPIClient struct {
	upsert *connect.Client[v1.NamespaceReq_Upsert, v1.NamespaceResp_Upsert]
	delete *connect.Client[v1.NamespaceReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.NamespaceReq_List, v1.NamespaceResp_List]
	watch  *connect.Client[v1.NamespaceReq_Watch, v1.NamespaceResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsNamespaceAPI.Upsert.
func (c *sGroupsNamespaceAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsNamespaceAPI.Delete.
func (c *sGroupsNamespaceAPIClient) Delete(ctx context.Context, req *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsNamespaceAPI.List.
func (c *sGroupsNamespaceAPIClient) List(ctx context.Context, req *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsNamespaceAPI.Watch.
func (c *sGroupsNamespaceAPIClient) Watch(ctx context.Context, req *connect.Request[v1.NamespaceReq_Watch]) (*connect.ServerStreamForClient[v1.NamespaceResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsNamespaceAPIHandler is an implementation of the sgroups.v1.SGroupsNamespaceAPI service.
type SGroupsNamespaceAPIHandler interface {
	// Upsert: Create or update namespace(es)
	Upsert(context.Context, *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceResp_Upsert], error)
	// Delete: Delete namespace(es)
	Delete(context.Context, *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List namespace(es)
	List(context.Context, *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceResp_List], error)
	// Watch: Watch namespace(es)
	Watch(context.Context, *connect.Request[v1.NamespaceReq_Watch], *connect.ServerStream[v1.NamespaceResp_Watch]) error
}

// NewSGroupsNamespaceAPIHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsNamespaceAPIHandler(svc SGroupsNamespaceAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsNamespaceAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNamespaceAPI").Methods()
	sGroupsNamespaceAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNamespaceAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNamespaceAPIListHandler := connect.NewUnaryHandler(
		SGroupsNamespaceAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNamespaceAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsNamespaceAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsNamespaceAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsNamespaceAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsNamespaceAPIUpsertProcedure:
			sGroupsNamespaceAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsNamespaceAPIDeleteProcedure:
			sGroupsNamespaceAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsNamespaceAPIListProcedure:
			sGroupsNamespaceAPIListHandler.ServeHTTP(w, r)
		case SGroupsNamespaceAPIWatchProcedure:
			sGroupsNamespaceAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsNamespaceAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsNamespaceAPIHandler struct{}

func (UnimplementedSGroupsNamespaceAPIHandler) Upsert(context.Context, *connect.Request[v1.NamespaceReq_Upsert]) (*connect.Response[v1.NamespaceResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsNamespaceAPIHandler) Delete(context.Context, *connect.Request[v1.NamespaceReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsNamespaceAPIHandler) List(context.Context, *connect.Request[v1.NamespaceReq_List]) (*connect.Response[v1.NamespaceResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.List is not implemented"))
}

func (UnimplementedSGroupsNamespaceAPIHandler) Watch(context.Context, *connect.Request[v1.NamespaceReq_Watch], *connect.ServerStream[v1.NamespaceResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNamespaceAPI.Watch is not implemented"))
}

// SGroupsAddressGroupsAPIClient is a client for the sgroups.v1.SGroupsAddressGroupsAPI service.
type SGroupsAddressGroupsAPIClient interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupResp_Upsert], error)
	// Delete: Delete address group(s)
	Delete(context.Context, *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List address group(s)
	List(context.Context, *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupResp_List], error)
	// Watch: Watch address group(s)
	Watch(context.Context, *connect.Request[v1.AddressGroupReq_Watch]) (*connect.ServerStreamForClient[v1.AddressGroupResp_Watch], error)
}

// NewSGroupsAddressGroupsAPIClient constructs a client for the sgroups.v1.SGroupsAddressGroupsAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsAddressGroupsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsAddressGroupsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsAddressGroupsAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsAddressGroupsAPI").Methods()
	return &sGroupsAddressGroupsAPIClient{
		upsert: connect.NewClient[v1.AddressGroupReq_Upsert, v1.AddressGroupResp_Upsert](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIUpsertProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.AddressGroupReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIDeleteProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.AddressGroupReq_List, v1.AddressGroupResp_List](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIListProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.AddressGroupReq_Watch, v1.AddressGroupResp_Watch](
			httpClient,
			baseURL+SGroupsAddressGroupsAPIWatchProcedure,
			connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsAddressGroupsAPIClient implements SGroupsAddressGroupsAPIClient.
type sGroupsAddressGroupsAPIClient struct {
	upsert *connect.Client[v1.AddressGroupReq_Upsert, v1.AddressGroupResp_Upsert]
	delete *connect.Client[v1.AddressGroupReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.AddressGroupReq_List, v1.AddressGroupResp_List]
	watch  *connect.Client[v1.AddressGroupReq_Watch, v1.AddressGroupResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsAddressGroupsAPI.Upsert.
func (c *sGroupsAddressGroupsAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsAddressGroupsAPI.Delete.
func (c *sGroupsAddressGroupsAPIClient) Delete(ctx context.Context, req *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsAddressGroupsAPI.List.
func (c *sGroupsAddressGroupsAPIClient) List(ctx context.Context, req *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsAddressGroupsAPI.Watch.
func (c *sGroupsAddressGroupsAPIClient) Watch(ctx context.Context, req *connect.Request[v1.AddressGroupReq_Watch]) (*connect.ServerStreamForClient[v1.AddressGroupResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsAddressGroupsAPIHandler is an implementation of the sgroups.v1.SGroupsAddressGroupsAPI
// service.
type SGroupsAddressGroupsAPIHandler interface {
	// Upsert: Create or update address group(s)
	Upsert(context.Context, *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupResp_Upsert], error)
	// Delete: Delete address group(s)
	Delete(context.Context, *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List address group(s)
	List(context.Context, *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupResp_List], error)
	// Watch: Watch address group(s)
	Watch(context.Context, *connect.Request[v1.AddressGroupReq_Watch], *connect.ServerStream[v1.AddressGroupResp_Watch]) error
}

// NewSGroupsAddressGroupsAPIHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsAddressGroupsAPIHandler(svc SGroupsAddressGroupsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsAddressGroupsAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsAddressGroupsAPI").Methods()
	sGroupsAddressGroupsAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsAddressGroupsAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsAddressGroupsAPIListHandler := connect.NewUnaryHandler(
		SGroupsAddressGroupsAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsAddressGroupsAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsAddressGroupsAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsAddressGroupsAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsAddressGroupsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsAddressGroupsAPIUpsertProcedure:
			sGroupsAddressGroupsAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsAddressGroupsAPIDeleteProcedure:
			sGroupsAddressGroupsAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsAddressGroupsAPIListProcedure:
			sGroupsAddressGroupsAPIListHandler.ServeHTTP(w, r)
		case SGroupsAddressGroupsAPIWatchProcedure:
			sGroupsAddressGroupsAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsAddressGroupsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsAddressGroupsAPIHandler struct{}

func (UnimplementedSGroupsAddressGroupsAPIHandler) Upsert(context.Context, *connect.Request[v1.AddressGroupReq_Upsert]) (*connect.Response[v1.AddressGroupResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsAddressGroupsAPIHandler) Delete(context.Context, *connect.Request[v1.AddressGroupReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsAddressGroupsAPIHandler) List(context.Context, *connect.Request[v1.AddressGroupReq_List]) (*connect.Response[v1.AddressGroupResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.List is not implemented"))
}

func (UnimplementedSGroupsAddressGroupsAPIHandler) Watch(context.Context, *connect.Request[v1.AddressGroupReq_Watch], *connect.ServerStream[v1.AddressGroupResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsAddressGroupsAPI.Watch is not implemented"))
}

// SGroupsNetworksAPIClient is a client for the sgroups.v1.SGroupsNetworksAPI service.
type SGroupsNetworksAPIClient interface {
	// Upsert: Create or update network(s)
	Upsert(context.Context, *connect.Request[v1.NetworkReq_Upsert]) (*connect.Response[v1.NetworkResp_Upsert], error)
	// Delete: Delete network(s)
	Delete(context.Context, *connect.Request[v1.NetworkReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List network(s)
	List(context.Context, *connect.Request[v1.NetworkReq_List]) (*connect.Response[v1.NetworkResp_List], error)
	// Watch: Watch network(s)
	Watch(context.Context, *connect.Request[v1.NetworkReq_Watch]) (*connect.ServerStreamForClient[v1.NetworkResp_Watch], error)
}

// NewSGroupsNetworksAPIClient constructs a client for the sgroups.v1.SGroupsNetworksAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsNetworksAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsNetworksAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsNetworksAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNetworksAPI").Methods()
	return &sGroupsNetworksAPIClient{
		upsert: connect.NewClient[v1.NetworkReq_Upsert, v1.NetworkResp_Upsert](
			httpClient,
			baseURL+SGroupsNetworksAPIUpsertProcedure,
			connect.WithSchema(sGroupsNetworksAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.NetworkReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsNetworksAPIDeleteProcedure,
			connect.WithSchema(sGroupsNetworksAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.NetworkReq_List, v1.NetworkResp_List](
			httpClient,
			baseURL+SGroupsNetworksAPIListProcedure,
			connect.WithSchema(sGroupsNetworksAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.NetworkReq_Watch, v1.NetworkResp_Watch](
			httpClient,
			baseURL+SGroupsNetworksAPIWatchProcedure,
			connect.WithSchema(sGroupsNetworksAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsNetworksAPIClient implements SGroupsNetworksAPIClient.
type sGroupsNetworksAPIClient struct {
	upsert *connect.Client[v1.NetworkReq_Upsert, v1.NetworkResp_Upsert]
	delete *connect.Client[v1.NetworkReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.NetworkReq_List, v1.NetworkResp_List]
	watch  *connect.Client[v1.NetworkReq_Watch, v1.NetworkResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsNetworksAPI.Upsert.
func (c *sGroupsNetworksAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.NetworkReq_Upsert]) (*connect.Response[v1.NetworkResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsNetworksAPI.Delete.
func (c *sGroupsNetworksAPIClient) Delete(ctx context.Context, req *connect.Request[v1.NetworkReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsNetworksAPI.List.
func (c *sGroupsNetworksAPIClient) List(ctx context.Context, req *connect.Request[v1.NetworkReq_List]) (*connect.Response[v1.NetworkResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsNetworksAPI.Watch.
func (c *sGroupsNetworksAPIClient) Watch(ctx context.Context, req *connect.Request[v1.NetworkReq_Watch]) (*connect.ServerStreamForClient[v1.NetworkResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsNetworksAPIHandler is an implementation of the sgroups.v1.SGroupsNetworksAPI service.
type SGroupsNetworksAPIHandler interface {
	// Upsert: Create or update network(s)
	Upsert(context.Context, *connect.Request[v1.NetworkReq_Upsert]) (*connect.Response[v1.NetworkResp_Upsert], error)
	// Delete: Delete network(s)
	Delete(context.Context, *connect.Request[v1.NetworkReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List network(s)
	List(context.Context, *connect.Request[v1.NetworkReq_List]) (*connect.Response[v1.NetworkResp_List], error)
	// Watch: Watch network(s)
	Watch(context.Context, *connect.Request[v1.NetworkReq_Watch], *connect.ServerStream[v1.NetworkResp_Watch]) error
}

// NewSGroupsNetworksAPIHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsNetworksAPIHandler(svc SGroupsNetworksAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsNetworksAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNetworksAPI").Methods()
	sGroupsNetworksAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsNetworksAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsNetworksAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNetworksAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsNetworksAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsNetworksAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNetworksAPIListHandler := connect.NewUnaryHandler(
		SGroupsNetworksAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsNetworksAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNetworksAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsNetworksAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsNetworksAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsNetworksAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsNetworksAPIUpsertProcedure:
			sGroupsNetworksAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsNetworksAPIDeleteProcedure:
			sGroupsNetworksAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsNetworksAPIListProcedure:
			sGroupsNetworksAPIListHandler.ServeHTTP(w, r)
		case SGroupsNetworksAPIWatchProcedure:
			sGroupsNetworksAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsNetworksAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsNetworksAPIHandler struct{}

func (UnimplementedSGroupsNetworksAPIHandler) Upsert(context.Context, *connect.Request[v1.NetworkReq_Upsert]) (*connect.Response[v1.NetworkResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworksAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsNetworksAPIHandler) Delete(context.Context, *connect.Request[v1.NetworkReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworksAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsNetworksAPIHandler) List(context.Context, *connect.Request[v1.NetworkReq_List]) (*connect.Response[v1.NetworkResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworksAPI.List is not implemented"))
}

func (UnimplementedSGroupsNetworksAPIHandler) Watch(context.Context, *connect.Request[v1.NetworkReq_Watch], *connect.ServerStream[v1.NetworkResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworksAPI.Watch is not implemented"))
}

// SGroupsHostsAPIClient is a client for the sgroups.v1.SGroupsHostsAPI service.
type SGroupsHostsAPIClient interface {
	// Upsert: Create or update host(s)
	Upsert(context.Context, *connect.Request[v1.HostReq_Upsert]) (*connect.Response[v1.HostResp_Upsert], error)
	// Delete: Delete host(s)
	Delete(context.Context, *connect.Request[v1.HostReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List host(s)
	List(context.Context, *connect.Request[v1.HostReq_List]) (*connect.Response[v1.HostResp_List], error)
	// Watch: Watch host(s)
	Watch(context.Context, *connect.Request[v1.HostReq_Watch]) (*connect.ServerStreamForClient[v1.HostResp_Watch], error)
	// UpdIPs: Update host(s) IPs
	UpdIPs(context.Context, *connect.Request[v1.HostReq_UpdIPs]) (*connect.Response[v1.HostResp_UpdIPs], error)
	// UpdMetaInfo: Update host(s) meta information
	UpdMetaInfo(context.Context, *connect.Request[v1.HostReq_UpdMetaInfo]) (*connect.Response[v1.HostResp_UpdMetaInfo], error)
}

// NewSGroupsHostsAPIClient constructs a client for the sgroups.v1.SGroupsHostsAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsHostsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsHostsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsHostsAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsHostsAPI").Methods()
	return &sGroupsHostsAPIClient{
		upsert: connect.NewClient[v1.HostReq_Upsert, v1.HostResp_Upsert](
			httpClient,
			baseURL+SGroupsHostsAPIUpsertProcedure,
			connect.WithSchema(sGroupsHostsAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.HostReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsHostsAPIDeleteProcedure,
			connect.WithSchema(sGroupsHostsAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.HostReq_List, v1.HostResp_List](
			httpClient,
			baseURL+SGroupsHostsAPIListProcedure,
			connect.WithSchema(sGroupsHostsAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.HostReq_Watch, v1.HostResp_Watch](
			httpClient,
			baseURL+SGroupsHostsAPIWatchProcedure,
			connect.WithSchema(sGroupsHostsAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
		updIPs: connect.NewClient[v1.HostReq_UpdIPs, v1.HostResp_UpdIPs](
			httpClient,
			baseURL+SGroupsHostsAPIUpdIPsProcedure,
			connect.WithSchema(sGroupsHostsAPIMethods.ByName("UpdIPs")),
			connect.WithClientOptions(opts...),
		),
		updMetaInfo: connect.NewClient[v1.HostReq_UpdMetaInfo, v1.HostResp_UpdMetaInfo](
			httpClient,
			baseURL+SGroupsHostsAPIUpdMetaInfoProcedure,
			connect.WithSchema(sGroupsHostsAPIMethods.ByName("UpdMetaInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsHostsAPIClient implements SGroupsHostsAPIClient.
type sGroupsHostsAPIClient struct {
	upsert      *connect.Client[v1.HostReq_Upsert, v1.HostResp_Upsert]
	delete      *connect.Client[v1.HostReq_Delete, emptypb.Empty]
	list        *connect.Client[v1.HostReq_List, v1.HostResp_List]
	watch       *connect.Client[v1.HostReq_Watch, v1.HostResp_Watch]
	updIPs      *connect.Client[v1.HostReq_UpdIPs, v1.HostResp_UpdIPs]
	updMetaInfo *connect.Client[v1.HostReq_UpdMetaInfo, v1.HostResp_UpdMetaInfo]
}

// Upsert calls sgroups.v1.SGroupsHostsAPI.Upsert.
func (c *sGroupsHostsAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.HostReq_Upsert]) (*connect.Response[v1.HostResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsHostsAPI.Delete.
func (c *sGroupsHostsAPIClient) Delete(ctx context.Context, req *connect.Request[v1.HostReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsHostsAPI.List.
func (c *sGroupsHostsAPIClient) List(ctx context.Context, req *connect.Request[v1.HostReq_List]) (*connect.Response[v1.HostResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsHostsAPI.Watch.
func (c *sGroupsHostsAPIClient) Watch(ctx context.Context, req *connect.Request[v1.HostReq_Watch]) (*connect.ServerStreamForClient[v1.HostResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// UpdIPs calls sgroups.v1.SGroupsHostsAPI.UpdIPs.
func (c *sGroupsHostsAPIClient) UpdIPs(ctx context.Context, req *connect.Request[v1.HostReq_UpdIPs]) (*connect.Response[v1.HostResp_UpdIPs], error) {
	return c.updIPs.CallUnary(ctx, req)
}

// UpdMetaInfo calls sgroups.v1.SGroupsHostsAPI.UpdMetaInfo.
func (c *sGroupsHostsAPIClient) UpdMetaInfo(ctx context.Context, req *connect.Request[v1.HostReq_UpdMetaInfo]) (*connect.Response[v1.HostResp_UpdMetaInfo], error) {
	return c.updMetaInfo.CallUnary(ctx, req)
}

// SGroupsHostsAPIHandler is an implementation of the sgroups.v1.SGroupsHostsAPI service.
type SGroupsHostsAPIHandler interface {
	// Upsert: Create or update host(s)
	Upsert(context.Context, *connect.Request[v1.HostReq_Upsert]) (*connect.Response[v1.HostResp_Upsert], error)
	// Delete: Delete host(s)
	Delete(context.Context, *connect.Request[v1.HostReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List host(s)
	List(context.Context, *connect.Request[v1.HostReq_List]) (*connect.Response[v1.HostResp_List], error)
	// Watch: Watch host(s)
	Watch(context.Context, *connect.Request[v1.HostReq_Watch], *connect.ServerStream[v1.HostResp_Watch]) error
	// UpdIPs: Update host(s) IPs
	UpdIPs(context.Context, *connect.Request[v1.HostReq_UpdIPs]) (*connect.Response[v1.HostResp_UpdIPs], error)
	// UpdMetaInfo: Update host(s) meta information
	UpdMetaInfo(context.Context, *connect.Request[v1.HostReq_UpdMetaInfo]) (*connect.Response[v1.HostResp_UpdMetaInfo], error)
}

// NewSGroupsHostsAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsHostsAPIHandler(svc SGroupsHostsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsHostsAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsHostsAPI").Methods()
	sGroupsHostsAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsHostsAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsHostsAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostsAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsHostsAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsHostsAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostsAPIListHandler := connect.NewUnaryHandler(
		SGroupsHostsAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsHostsAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostsAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsHostsAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsHostsAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostsAPIUpdIPsHandler := connect.NewUnaryHandler(
		SGroupsHostsAPIUpdIPsProcedure,
		svc.UpdIPs,
		connect.WithSchema(sGroupsHostsAPIMethods.ByName("UpdIPs")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostsAPIUpdMetaInfoHandler := connect.NewUnaryHandler(
		SGroupsHostsAPIUpdMetaInfoProcedure,
		svc.UpdMetaInfo,
		connect.WithSchema(sGroupsHostsAPIMethods.ByName("UpdMetaInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsHostsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsHostsAPIUpsertProcedure:
			sGroupsHostsAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsHostsAPIDeleteProcedure:
			sGroupsHostsAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsHostsAPIListProcedure:
			sGroupsHostsAPIListHandler.ServeHTTP(w, r)
		case SGroupsHostsAPIWatchProcedure:
			sGroupsHostsAPIWatchHandler.ServeHTTP(w, r)
		case SGroupsHostsAPIUpdIPsProcedure:
			sGroupsHostsAPIUpdIPsHandler.ServeHTTP(w, r)
		case SGroupsHostsAPIUpdMetaInfoProcedure:
			sGroupsHostsAPIUpdMetaInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsHostsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsHostsAPIHandler struct{}

func (UnimplementedSGroupsHostsAPIHandler) Upsert(context.Context, *connect.Request[v1.HostReq_Upsert]) (*connect.Response[v1.HostResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostsAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsHostsAPIHandler) Delete(context.Context, *connect.Request[v1.HostReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostsAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsHostsAPIHandler) List(context.Context, *connect.Request[v1.HostReq_List]) (*connect.Response[v1.HostResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostsAPI.List is not implemented"))
}

func (UnimplementedSGroupsHostsAPIHandler) Watch(context.Context, *connect.Request[v1.HostReq_Watch], *connect.ServerStream[v1.HostResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostsAPI.Watch is not implemented"))
}

func (UnimplementedSGroupsHostsAPIHandler) UpdIPs(context.Context, *connect.Request[v1.HostReq_UpdIPs]) (*connect.Response[v1.HostResp_UpdIPs], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostsAPI.UpdIPs is not implemented"))
}

func (UnimplementedSGroupsHostsAPIHandler) UpdMetaInfo(context.Context, *connect.Request[v1.HostReq_UpdMetaInfo]) (*connect.Response[v1.HostResp_UpdMetaInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostsAPI.UpdMetaInfo is not implemented"))
}

// SGroupsHostBindingAPIClient is a client for the sgroups.v1.SGroupsHostBindingAPI service.
type SGroupsHostBindingAPIClient interface {
	// Upsert: Create or update host binding(s)
	Upsert(context.Context, *connect.Request[v1.HostBindingReq_Upsert]) (*connect.Response[v1.HostBindingResp_Upsert], error)
	// Delete: Delete host binding(s)
	Delete(context.Context, *connect.Request[v1.HostBindingReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List host binding(s)
	List(context.Context, *connect.Request[v1.HostBindingReq_List]) (*connect.Response[v1.HostBindingResp_List], error)
	// Watch: Watch host binding(s)
	Watch(context.Context, *connect.Request[v1.HostBindingReq_Watch]) (*connect.ServerStreamForClient[v1.HostBindingResp_Watch], error)
}

// NewSGroupsHostBindingAPIClient constructs a client for the sgroups.v1.SGroupsHostBindingAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsHostBindingAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsHostBindingAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsHostBindingAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsHostBindingAPI").Methods()
	return &sGroupsHostBindingAPIClient{
		upsert: connect.NewClient[v1.HostBindingReq_Upsert, v1.HostBindingResp_Upsert](
			httpClient,
			baseURL+SGroupsHostBindingAPIUpsertProcedure,
			connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.HostBindingReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsHostBindingAPIDeleteProcedure,
			connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.HostBindingReq_List, v1.HostBindingResp_List](
			httpClient,
			baseURL+SGroupsHostBindingAPIListProcedure,
			connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.HostBindingReq_Watch, v1.HostBindingResp_Watch](
			httpClient,
			baseURL+SGroupsHostBindingAPIWatchProcedure,
			connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsHostBindingAPIClient implements SGroupsHostBindingAPIClient.
type sGroupsHostBindingAPIClient struct {
	upsert *connect.Client[v1.HostBindingReq_Upsert, v1.HostBindingResp_Upsert]
	delete *connect.Client[v1.HostBindingReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.HostBindingReq_List, v1.HostBindingResp_List]
	watch  *connect.Client[v1.HostBindingReq_Watch, v1.HostBindingResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsHostBindingAPI.Upsert.
func (c *sGroupsHostBindingAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.HostBindingReq_Upsert]) (*connect.Response[v1.HostBindingResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsHostBindingAPI.Delete.
func (c *sGroupsHostBindingAPIClient) Delete(ctx context.Context, req *connect.Request[v1.HostBindingReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsHostBindingAPI.List.
func (c *sGroupsHostBindingAPIClient) List(ctx context.Context, req *connect.Request[v1.HostBindingReq_List]) (*connect.Response[v1.HostBindingResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsHostBindingAPI.Watch.
func (c *sGroupsHostBindingAPIClient) Watch(ctx context.Context, req *connect.Request[v1.HostBindingReq_Watch]) (*connect.ServerStreamForClient[v1.HostBindingResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsHostBindingAPIHandler is an implementation of the sgroups.v1.SGroupsHostBindingAPI
// service.
type SGroupsHostBindingAPIHandler interface {
	// Upsert: Create or update host binding(s)
	Upsert(context.Context, *connect.Request[v1.HostBindingReq_Upsert]) (*connect.Response[v1.HostBindingResp_Upsert], error)
	// Delete: Delete host binding(s)
	Delete(context.Context, *connect.Request[v1.HostBindingReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List host binding(s)
	List(context.Context, *connect.Request[v1.HostBindingReq_List]) (*connect.Response[v1.HostBindingResp_List], error)
	// Watch: Watch host binding(s)
	Watch(context.Context, *connect.Request[v1.HostBindingReq_Watch], *connect.ServerStream[v1.HostBindingResp_Watch]) error
}

// NewSGroupsHostBindingAPIHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsHostBindingAPIHandler(svc SGroupsHostBindingAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsHostBindingAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsHostBindingAPI").Methods()
	sGroupsHostBindingAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsHostBindingAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostBindingAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsHostBindingAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostBindingAPIListHandler := connect.NewUnaryHandler(
		SGroupsHostBindingAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsHostBindingAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsHostBindingAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsHostBindingAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsHostBindingAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsHostBindingAPIUpsertProcedure:
			sGroupsHostBindingAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsHostBindingAPIDeleteProcedure:
			sGroupsHostBindingAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsHostBindingAPIListProcedure:
			sGroupsHostBindingAPIListHandler.ServeHTTP(w, r)
		case SGroupsHostBindingAPIWatchProcedure:
			sGroupsHostBindingAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsHostBindingAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsHostBindingAPIHandler struct{}

func (UnimplementedSGroupsHostBindingAPIHandler) Upsert(context.Context, *connect.Request[v1.HostBindingReq_Upsert]) (*connect.Response[v1.HostBindingResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostBindingAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsHostBindingAPIHandler) Delete(context.Context, *connect.Request[v1.HostBindingReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostBindingAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsHostBindingAPIHandler) List(context.Context, *connect.Request[v1.HostBindingReq_List]) (*connect.Response[v1.HostBindingResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostBindingAPI.List is not implemented"))
}

func (UnimplementedSGroupsHostBindingAPIHandler) Watch(context.Context, *connect.Request[v1.HostBindingReq_Watch], *connect.ServerStream[v1.HostBindingResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsHostBindingAPI.Watch is not implemented"))
}

// SGroupsNetworkBindingAPIClient is a client for the sgroups.v1.SGroupsNetworkBindingAPI service.
type SGroupsNetworkBindingAPIClient interface {
	// Upsert: Create or update network binding(s)
	Upsert(context.Context, *connect.Request[v1.NetworkBindingReq_Upsert]) (*connect.Response[v1.NetworkBindingResp_Upsert], error)
	// Delete: Delete network binding(s)
	Delete(context.Context, *connect.Request[v1.NetworkBindingReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List network binding(s)
	List(context.Context, *connect.Request[v1.NetworkBindingReq_List]) (*connect.Response[v1.NetworkBindingResp_List], error)
	// Watch: Watch network binding(s)
	Watch(context.Context, *connect.Request[v1.NetworkBindingReq_Watch]) (*connect.ServerStreamForClient[v1.NetworkBindingResp_Watch], error)
}

// NewSGroupsNetworkBindingAPIClient constructs a client for the sgroups.v1.SGroupsNetworkBindingAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsNetworkBindingAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsNetworkBindingAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsNetworkBindingAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNetworkBindingAPI").Methods()
	return &sGroupsNetworkBindingAPIClient{
		upsert: connect.NewClient[v1.NetworkBindingReq_Upsert, v1.NetworkBindingResp_Upsert](
			httpClient,
			baseURL+SGroupsNetworkBindingAPIUpsertProcedure,
			connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.NetworkBindingReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsNetworkBindingAPIDeleteProcedure,
			connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.NetworkBindingReq_List, v1.NetworkBindingResp_List](
			httpClient,
			baseURL+SGroupsNetworkBindingAPIListProcedure,
			connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.NetworkBindingReq_Watch, v1.NetworkBindingResp_Watch](
			httpClient,
			baseURL+SGroupsNetworkBindingAPIWatchProcedure,
			connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsNetworkBindingAPIClient implements SGroupsNetworkBindingAPIClient.
type sGroupsNetworkBindingAPIClient struct {
	upsert *connect.Client[v1.NetworkBindingReq_Upsert, v1.NetworkBindingResp_Upsert]
	delete *connect.Client[v1.NetworkBindingReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.NetworkBindingReq_List, v1.NetworkBindingResp_List]
	watch  *connect.Client[v1.NetworkBindingReq_Watch, v1.NetworkBindingResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsNetworkBindingAPI.Upsert.
func (c *sGroupsNetworkBindingAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.NetworkBindingReq_Upsert]) (*connect.Response[v1.NetworkBindingResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsNetworkBindingAPI.Delete.
func (c *sGroupsNetworkBindingAPIClient) Delete(ctx context.Context, req *connect.Request[v1.NetworkBindingReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsNetworkBindingAPI.List.
func (c *sGroupsNetworkBindingAPIClient) List(ctx context.Context, req *connect.Request[v1.NetworkBindingReq_List]) (*connect.Response[v1.NetworkBindingResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsNetworkBindingAPI.Watch.
func (c *sGroupsNetworkBindingAPIClient) Watch(ctx context.Context, req *connect.Request[v1.NetworkBindingReq_Watch]) (*connect.ServerStreamForClient[v1.NetworkBindingResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsNetworkBindingAPIHandler is an implementation of the sgroups.v1.SGroupsNetworkBindingAPI
// service.
type SGroupsNetworkBindingAPIHandler interface {
	// Upsert: Create or update network binding(s)
	Upsert(context.Context, *connect.Request[v1.NetworkBindingReq_Upsert]) (*connect.Response[v1.NetworkBindingResp_Upsert], error)
	// Delete: Delete network binding(s)
	Delete(context.Context, *connect.Request[v1.NetworkBindingReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List network binding(s)
	List(context.Context, *connect.Request[v1.NetworkBindingReq_List]) (*connect.Response[v1.NetworkBindingResp_List], error)
	// Watch: Watch network binding(s)
	Watch(context.Context, *connect.Request[v1.NetworkBindingReq_Watch], *connect.ServerStream[v1.NetworkBindingResp_Watch]) error
}

// NewSGroupsNetworkBindingAPIHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsNetworkBindingAPIHandler(svc SGroupsNetworkBindingAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsNetworkBindingAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsNetworkBindingAPI").Methods()
	sGroupsNetworkBindingAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsNetworkBindingAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNetworkBindingAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsNetworkBindingAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNetworkBindingAPIListHandler := connect.NewUnaryHandler(
		SGroupsNetworkBindingAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsNetworkBindingAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsNetworkBindingAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsNetworkBindingAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsNetworkBindingAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsNetworkBindingAPIUpsertProcedure:
			sGroupsNetworkBindingAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsNetworkBindingAPIDeleteProcedure:
			sGroupsNetworkBindingAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsNetworkBindingAPIListProcedure:
			sGroupsNetworkBindingAPIListHandler.ServeHTTP(w, r)
		case SGroupsNetworkBindingAPIWatchProcedure:
			sGroupsNetworkBindingAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsNetworkBindingAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsNetworkBindingAPIHandler struct{}

func (UnimplementedSGroupsNetworkBindingAPIHandler) Upsert(context.Context, *connect.Request[v1.NetworkBindingReq_Upsert]) (*connect.Response[v1.NetworkBindingResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworkBindingAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsNetworkBindingAPIHandler) Delete(context.Context, *connect.Request[v1.NetworkBindingReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworkBindingAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsNetworkBindingAPIHandler) List(context.Context, *connect.Request[v1.NetworkBindingReq_List]) (*connect.Response[v1.NetworkBindingResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworkBindingAPI.List is not implemented"))
}

func (UnimplementedSGroupsNetworkBindingAPIHandler) Watch(context.Context, *connect.Request[v1.NetworkBindingReq_Watch], *connect.ServerStream[v1.NetworkBindingResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsNetworkBindingAPI.Watch is not implemented"))
}

// SGroupsServicesAPIClient is a client for the sgroups.v1.SGroupsServicesAPI service.
type SGroupsServicesAPIClient interface {
	// Upsert: Create or update service(s)
	Upsert(context.Context, *connect.Request[v1.ServiceReq_Upsert]) (*connect.Response[v1.ServiceResp_Upsert], error)
	// Delete: Delete service(s)
	Delete(context.Context, *connect.Request[v1.ServiceReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List service(s)
	List(context.Context, *connect.Request[v1.ServiceReq_List]) (*connect.Response[v1.ServiceResp_List], error)
	// Watch: Watch service(s)
	Watch(context.Context, *connect.Request[v1.ServiceReq_Watch]) (*connect.ServerStreamForClient[v1.ServiceResp_Watch], error)
}

// NewSGroupsServicesAPIClient constructs a client for the sgroups.v1.SGroupsServicesAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsServicesAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsServicesAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsServicesAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsServicesAPI").Methods()
	return &sGroupsServicesAPIClient{
		upsert: connect.NewClient[v1.ServiceReq_Upsert, v1.ServiceResp_Upsert](
			httpClient,
			baseURL+SGroupsServicesAPIUpsertProcedure,
			connect.WithSchema(sGroupsServicesAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.ServiceReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsServicesAPIDeleteProcedure,
			connect.WithSchema(sGroupsServicesAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ServiceReq_List, v1.ServiceResp_List](
			httpClient,
			baseURL+SGroupsServicesAPIListProcedure,
			connect.WithSchema(sGroupsServicesAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.ServiceReq_Watch, v1.ServiceResp_Watch](
			httpClient,
			baseURL+SGroupsServicesAPIWatchProcedure,
			connect.WithSchema(sGroupsServicesAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsServicesAPIClient implements SGroupsServicesAPIClient.
type sGroupsServicesAPIClient struct {
	upsert *connect.Client[v1.ServiceReq_Upsert, v1.ServiceResp_Upsert]
	delete *connect.Client[v1.ServiceReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.ServiceReq_List, v1.ServiceResp_List]
	watch  *connect.Client[v1.ServiceReq_Watch, v1.ServiceResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsServicesAPI.Upsert.
func (c *sGroupsServicesAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.ServiceReq_Upsert]) (*connect.Response[v1.ServiceResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsServicesAPI.Delete.
func (c *sGroupsServicesAPIClient) Delete(ctx context.Context, req *connect.Request[v1.ServiceReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsServicesAPI.List.
func (c *sGroupsServicesAPIClient) List(ctx context.Context, req *connect.Request[v1.ServiceReq_List]) (*connect.Response[v1.ServiceResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsServicesAPI.Watch.
func (c *sGroupsServicesAPIClient) Watch(ctx context.Context, req *connect.Request[v1.ServiceReq_Watch]) (*connect.ServerStreamForClient[v1.ServiceResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsServicesAPIHandler is an implementation of the sgroups.v1.SGroupsServicesAPI service.
type SGroupsServicesAPIHandler interface {
	// Upsert: Create or update service(s)
	Upsert(context.Context, *connect.Request[v1.ServiceReq_Upsert]) (*connect.Response[v1.ServiceResp_Upsert], error)
	// Delete: Delete service(s)
	Delete(context.Context, *connect.Request[v1.ServiceReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List service(s)
	List(context.Context, *connect.Request[v1.ServiceReq_List]) (*connect.Response[v1.ServiceResp_List], error)
	// Watch: Watch service(s)
	Watch(context.Context, *connect.Request[v1.ServiceReq_Watch], *connect.ServerStream[v1.ServiceResp_Watch]) error
}

// NewSGroupsServicesAPIHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsServicesAPIHandler(svc SGroupsServicesAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsServicesAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsServicesAPI").Methods()
	sGroupsServicesAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsServicesAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsServicesAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsServicesAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsServicesAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsServicesAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsServicesAPIListHandler := connect.NewUnaryHandler(
		SGroupsServicesAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsServicesAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsServicesAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsServicesAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsServicesAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsServicesAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsServicesAPIUpsertProcedure:
			sGroupsServicesAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsServicesAPIDeleteProcedure:
			sGroupsServicesAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsServicesAPIListProcedure:
			sGroupsServicesAPIListHandler.ServeHTTP(w, r)
		case SGroupsServicesAPIWatchProcedure:
			sGroupsServicesAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsServicesAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsServicesAPIHandler struct{}

func (UnimplementedSGroupsServicesAPIHandler) Upsert(context.Context, *connect.Request[v1.ServiceReq_Upsert]) (*connect.Response[v1.ServiceResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServicesAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsServicesAPIHandler) Delete(context.Context, *connect.Request[v1.ServiceReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServicesAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsServicesAPIHandler) List(context.Context, *connect.Request[v1.ServiceReq_List]) (*connect.Response[v1.ServiceResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServicesAPI.List is not implemented"))
}

func (UnimplementedSGroupsServicesAPIHandler) Watch(context.Context, *connect.Request[v1.ServiceReq_Watch], *connect.ServerStream[v1.ServiceResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServicesAPI.Watch is not implemented"))
}

// SGroupsServiceBindingAPIClient is a client for the sgroups.v1.SGroupsServiceBindingAPI service.
type SGroupsServiceBindingAPIClient interface {
	// Upsert: Create or update service binding(s)
	Upsert(context.Context, *connect.Request[v1.ServiceBindingReq_Upsert]) (*connect.Response[v1.ServiceBindingResp_Upsert], error)
	// Delete: Delete service binding(s)
	Delete(context.Context, *connect.Request[v1.ServiceBindingReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List service binding(s)
	List(context.Context, *connect.Request[v1.ServiceBindingReq_List]) (*connect.Response[v1.ServiceBindingResp_List], error)
	// Watch: Watch service binding(s)
	Watch(context.Context, *connect.Request[v1.ServiceBindingReq_Watch]) (*connect.ServerStreamForClient[v1.ServiceBindingResp_Watch], error)
}

// NewSGroupsServiceBindingAPIClient constructs a client for the sgroups.v1.SGroupsServiceBindingAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsServiceBindingAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsServiceBindingAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsServiceBindingAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsServiceBindingAPI").Methods()
	return &sGroupsServiceBindingAPIClient{
		upsert: connect.NewClient[v1.ServiceBindingReq_Upsert, v1.ServiceBindingResp_Upsert](
			httpClient,
			baseURL+SGroupsServiceBindingAPIUpsertProcedure,
			connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.ServiceBindingReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsServiceBindingAPIDeleteProcedure,
			connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ServiceBindingReq_List, v1.ServiceBindingResp_List](
			httpClient,
			baseURL+SGroupsServiceBindingAPIListProcedure,
			connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.ServiceBindingReq_Watch, v1.ServiceBindingResp_Watch](
			httpClient,
			baseURL+SGroupsServiceBindingAPIWatchProcedure,
			connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsServiceBindingAPIClient implements SGroupsServiceBindingAPIClient.
type sGroupsServiceBindingAPIClient struct {
	upsert *connect.Client[v1.ServiceBindingReq_Upsert, v1.ServiceBindingResp_Upsert]
	delete *connect.Client[v1.ServiceBindingReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.ServiceBindingReq_List, v1.ServiceBindingResp_List]
	watch  *connect.Client[v1.ServiceBindingReq_Watch, v1.ServiceBindingResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsServiceBindingAPI.Upsert.
func (c *sGroupsServiceBindingAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.ServiceBindingReq_Upsert]) (*connect.Response[v1.ServiceBindingResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsServiceBindingAPI.Delete.
func (c *sGroupsServiceBindingAPIClient) Delete(ctx context.Context, req *connect.Request[v1.ServiceBindingReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsServiceBindingAPI.List.
func (c *sGroupsServiceBindingAPIClient) List(ctx context.Context, req *connect.Request[v1.ServiceBindingReq_List]) (*connect.Response[v1.ServiceBindingResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsServiceBindingAPI.Watch.
func (c *sGroupsServiceBindingAPIClient) Watch(ctx context.Context, req *connect.Request[v1.ServiceBindingReq_Watch]) (*connect.ServerStreamForClient[v1.ServiceBindingResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsServiceBindingAPIHandler is an implementation of the sgroups.v1.SGroupsServiceBindingAPI
// service.
type SGroupsServiceBindingAPIHandler interface {
	// Upsert: Create or update service binding(s)
	Upsert(context.Context, *connect.Request[v1.ServiceBindingReq_Upsert]) (*connect.Response[v1.ServiceBindingResp_Upsert], error)
	// Delete: Delete service binding(s)
	Delete(context.Context, *connect.Request[v1.ServiceBindingReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List service binding(s)
	List(context.Context, *connect.Request[v1.ServiceBindingReq_List]) (*connect.Response[v1.ServiceBindingResp_List], error)
	// Watch: Watch service binding(s)
	Watch(context.Context, *connect.Request[v1.ServiceBindingReq_Watch], *connect.ServerStream[v1.ServiceBindingResp_Watch]) error
}

// NewSGroupsServiceBindingAPIHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsServiceBindingAPIHandler(svc SGroupsServiceBindingAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsServiceBindingAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsServiceBindingAPI").Methods()
	sGroupsServiceBindingAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsServiceBindingAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsServiceBindingAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsServiceBindingAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsServiceBindingAPIListHandler := connect.NewUnaryHandler(
		SGroupsServiceBindingAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsServiceBindingAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsServiceBindingAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsServiceBindingAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsServiceBindingAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsServiceBindingAPIUpsertProcedure:
			sGroupsServiceBindingAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsServiceBindingAPIDeleteProcedure:
			sGroupsServiceBindingAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsServiceBindingAPIListProcedure:
			sGroupsServiceBindingAPIListHandler.ServeHTTP(w, r)
		case SGroupsServiceBindingAPIWatchProcedure:
			sGroupsServiceBindingAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsServiceBindingAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsServiceBindingAPIHandler struct{}

func (UnimplementedSGroupsServiceBindingAPIHandler) Upsert(context.Context, *connect.Request[v1.ServiceBindingReq_Upsert]) (*connect.Response[v1.ServiceBindingResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServiceBindingAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsServiceBindingAPIHandler) Delete(context.Context, *connect.Request[v1.ServiceBindingReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServiceBindingAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsServiceBindingAPIHandler) List(context.Context, *connect.Request[v1.ServiceBindingReq_List]) (*connect.Response[v1.ServiceBindingResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServiceBindingAPI.List is not implemented"))
}

func (UnimplementedSGroupsServiceBindingAPIHandler) Watch(context.Context, *connect.Request[v1.ServiceBindingReq_Watch], *connect.ServerStream[v1.ServiceBindingResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsServiceBindingAPI.Watch is not implemented"))
}

// SGroupsRulesAPIClient is a client for the sgroups.v1.SGroupsRulesAPI service.
type SGroupsRulesAPIClient interface {
	// Upsert: Create or update rules
	Upsert(context.Context, *connect.Request[v1.RuleReq_Upsert]) (*connect.Response[v1.RuleResp_Upsert], error)
	// Delete: Delete rules
	Delete(context.Context, *connect.Request[v1.RuleReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List rules
	List(context.Context, *connect.Request[v1.RuleReq_List]) (*connect.Response[v1.RuleResp_List], error)
	// Watch: Watch rules
	Watch(context.Context, *connect.Request[v1.RuleReq_Watch]) (*connect.ServerStreamForClient[v1.RuleResp_Watch], error)
}

// NewSGroupsRulesAPIClient constructs a client for the sgroups.v1.SGroupsRulesAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsRulesAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsRulesAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsRulesAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsRulesAPI").Methods()
	return &sGroupsRulesAPIClient{
		upsert: connect.NewClient[v1.RuleReq_Upsert, v1.RuleResp_Upsert](
			httpClient,
			baseURL+SGroupsRulesAPIUpsertProcedure,
			connect.WithSchema(sGroupsRulesAPIMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.RuleReq_Delete, emptypb.Empty](
			httpClient,
			baseURL+SGroupsRulesAPIDeleteProcedure,
			connect.WithSchema(sGroupsRulesAPIMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.RuleReq_List, v1.RuleResp_List](
			httpClient,
			baseURL+SGroupsRulesAPIListProcedure,
			connect.WithSchema(sGroupsRulesAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.RuleReq_Watch, v1.RuleResp_Watch](
			httpClient,
			baseURL+SGroupsRulesAPIWatchProcedure,
			connect.WithSchema(sGroupsRulesAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsRulesAPIClient implements SGroupsRulesAPIClient.
type sGroupsRulesAPIClient struct {
	upsert *connect.Client[v1.RuleReq_Upsert, v1.RuleResp_Upsert]
	delete *connect.Client[v1.RuleReq_Delete, emptypb.Empty]
	list   *connect.Client[v1.RuleReq_List, v1.RuleResp_List]
	watch  *connect.Client[v1.RuleReq_Watch, v1.RuleResp_Watch]
}

// Upsert calls sgroups.v1.SGroupsRulesAPI.Upsert.
func (c *sGroupsRulesAPIClient) Upsert(ctx context.Context, req *connect.Request[v1.RuleReq_Upsert]) (*connect.Response[v1.RuleResp_Upsert], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls sgroups.v1.SGroupsRulesAPI.Delete.
func (c *sGroupsRulesAPIClient) Delete(ctx context.Context, req *connect.Request[v1.RuleReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls sgroups.v1.SGroupsRulesAPI.List.
func (c *sGroupsRulesAPIClient) List(ctx context.Context, req *connect.Request[v1.RuleReq_List]) (*connect.Response[v1.RuleResp_List], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsRulesAPI.Watch.
func (c *sGroupsRulesAPIClient) Watch(ctx context.Context, req *connect.Request[v1.RuleReq_Watch]) (*connect.ServerStreamForClient[v1.RuleResp_Watch], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsRulesAPIHandler is an implementation of the sgroups.v1.SGroupsRulesAPI service.
type SGroupsRulesAPIHandler interface {
	// Upsert: Create or update rules
	Upsert(context.Context, *connect.Request[v1.RuleReq_Upsert]) (*connect.Response[v1.RuleResp_Upsert], error)
	// Delete: Delete rules
	Delete(context.Context, *connect.Request[v1.RuleReq_Delete]) (*connect.Response[emptypb.Empty], error)
	// List: List rules
	List(context.Context, *connect.Request[v1.RuleReq_List]) (*connect.Response[v1.RuleResp_List], error)
	// Watch: Watch rules
	Watch(context.Context, *connect.Request[v1.RuleReq_Watch], *connect.ServerStream[v1.RuleResp_Watch]) error
}

// NewSGroupsRulesAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsRulesAPIHandler(svc SGroupsRulesAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsRulesAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsRulesAPI").Methods()
	sGroupsRulesAPIUpsertHandler := connect.NewUnaryHandler(
		SGroupsRulesAPIUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(sGroupsRulesAPIMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsRulesAPIDeleteHandler := connect.NewUnaryHandler(
		SGroupsRulesAPIDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sGroupsRulesAPIMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsRulesAPIListHandler := connect.NewUnaryHandler(
		SGroupsRulesAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsRulesAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsRulesAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsRulesAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsRulesAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsRulesAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsRulesAPIUpsertProcedure:
			sGroupsRulesAPIUpsertHandler.ServeHTTP(w, r)
		case SGroupsRulesAPIDeleteProcedure:
			sGroupsRulesAPIDeleteHandler.ServeHTTP(w, r)
		case SGroupsRulesAPIListProcedure:
			sGroupsRulesAPIListHandler.ServeHTTP(w, r)
		case SGroupsRulesAPIWatchProcedure:
			sGroupsRulesAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsRulesAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsRulesAPIHandler struct{}

func (UnimplementedSGroupsRulesAPIHandler) Upsert(context.Context, *connect.Request[v1.RuleReq_Upsert]) (*connect.Response[v1.RuleResp_Upsert], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsRulesAPI.Upsert is not implemented"))
}

func (UnimplementedSGroupsRulesAPIHandler) Delete(context.Context, *connect.Request[v1.RuleReq_Delete]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsRulesAPI.Delete is not implemented"))
}

func (UnimplementedSGroupsRulesAPIHandler) List(context.Context, *connect.Request[v1.RuleReq_List]) (*connect.Response[v1.RuleResp_List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsRulesAPI.List is not implemented"))
}

func (UnimplementedSGroupsRulesAPIHandler) Watch(context.Context, *connect.Request[v1.RuleReq_Watch], *connect.ServerStream[v1.RuleResp_Watch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsRulesAPI.Watch is not implemented"))
}

// SGroupsStatusAPIClient is a client for the sgroups.v1.SGroupsStatusAPI service.
type SGroupsStatusAPIClient interface {
	// List: gets last succeeded update DB status
	List(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.SyncStatusResp], error)
	// Watch: gets stream of update DB statuses
	Watch(context.Context, *connect.Request[emptypb.Empty]) (*connect.ServerStreamForClient[v1.SyncStatusResp], error)
}

// NewSGroupsStatusAPIClient constructs a client for the sgroups.v1.SGroupsStatusAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSGroupsStatusAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SGroupsStatusAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sGroupsStatusAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsStatusAPI").Methods()
	return &sGroupsStatusAPIClient{
		list: connect.NewClient[emptypb.Empty, v1.SyncStatusResp](
			httpClient,
			baseURL+SGroupsStatusAPIListProcedure,
			connect.WithSchema(sGroupsStatusAPIMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[emptypb.Empty, v1.SyncStatusResp](
			httpClient,
			baseURL+SGroupsStatusAPIWatchProcedure,
			connect.WithSchema(sGroupsStatusAPIMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sGroupsStatusAPIClient implements SGroupsStatusAPIClient.
type sGroupsStatusAPIClient struct {
	list  *connect.Client[emptypb.Empty, v1.SyncStatusResp]
	watch *connect.Client[emptypb.Empty, v1.SyncStatusResp]
}

// List calls sgroups.v1.SGroupsStatusAPI.List.
func (c *sGroupsStatusAPIClient) List(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.SyncStatusResp], error) {
	return c.list.CallUnary(ctx, req)
}

// Watch calls sgroups.v1.SGroupsStatusAPI.Watch.
func (c *sGroupsStatusAPIClient) Watch(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.ServerStreamForClient[v1.SyncStatusResp], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SGroupsStatusAPIHandler is an implementation of the sgroups.v1.SGroupsStatusAPI service.
type SGroupsStatusAPIHandler interface {
	// List: gets last succeeded update DB status
	List(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.SyncStatusResp], error)
	// Watch: gets stream of update DB statuses
	Watch(context.Context, *connect.Request[emptypb.Empty], *connect.ServerStream[v1.SyncStatusResp]) error
}

// NewSGroupsStatusAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSGroupsStatusAPIHandler(svc SGroupsStatusAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sGroupsStatusAPIMethods := v1.File_sgroups_v1_services_proto.Services().ByName("SGroupsStatusAPI").Methods()
	sGroupsStatusAPIListHandler := connect.NewUnaryHandler(
		SGroupsStatusAPIListProcedure,
		svc.List,
		connect.WithSchema(sGroupsStatusAPIMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sGroupsStatusAPIWatchHandler := connect.NewServerStreamHandler(
		SGroupsStatusAPIWatchProcedure,
		svc.Watch,
		connect.WithSchema(sGroupsStatusAPIMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sgroups.v1.SGroupsStatusAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SGroupsStatusAPIListProcedure:
			sGroupsStatusAPIListHandler.ServeHTTP(w, r)
		case SGroupsStatusAPIWatchProcedure:
			sGroupsStatusAPIWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSGroupsStatusAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSGroupsStatusAPIHandler struct{}

func (UnimplementedSGroupsStatusAPIHandler) List(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.SyncStatusResp], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsStatusAPI.List is not implemented"))
}

func (UnimplementedSGroupsStatusAPIHandler) Watch(context.Context, *connect.Request[emptypb.Empty], *connect.ServerStream[v1.SyncStatusResp]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sgroups.v1.SGroupsStatusAPI.Watch is not implemented"))
}
